### ISSUE TITLE
suggestion: add notes on support for other devices than trezor

### ISSUE THREAD

**Issue by gretel** [romanz/trezor-agent#102]
if i get it right at least *keepkey* is supported? that'd be good to know for people not glimpsing into the source code, i'd suggest. regards

**Comment by romanz** [comment]
Yes, this project supports both TREZOR, KeepKey and Ledger Nano S devices :)
The documentation is indeed a bit lacking - so thanks for opening the issue!

**Comment by romanz** [comment]
Regarding KeepKey usage instructions, please see:
https://support.keepkey.com/support/solutions/articles/6000106779-ssh-keepkey-configuration-with-ubuntu-linux-

**Comment by gretel** [comment]
@romanz `We are sorry. This portal is not available at your location.`
