### ISSUE TITLE
unable to enter pin without numeric keypad installed

### ISSUE THREAD

**Issue by gretel** [romanz/trezor-agent#103]
on invocation of `trezor-agent`:
```Use the numeric keypad to describe number positions.```
unfortunately, my macbook has none.

**Comment by romanz** [comment]
You can enter the PIN using the regular number keys, following the instructions here:
https://github.com/trezor/python-trezor#pin-entering

**Comment by gretel** [comment]
oh, doh, stupid me. thanks for the guidance.

**Comment by romanz** [comment]
No problem :)
