### ISSUE TITLE
trezor-gpg not found

### ISSUE THREAD

**Issue by Z819** [romanz/trezor-agent#123]
`./scripts/gpg-init "e65H <e65H>"                                                                                          
./scripts/gpg-init: line 18: trezor-gpg: command not found
`
Managed to install it locally (--user) but stuck here.
In other log outputs I saw `/usr/local/*/trezor-gpg`
Do I miss something?

I installed `python2-trezor-0.7.13` already.

I'm on Fedora 25.

Thank you.

**Comment by romanz** [comment]
Thanks for reporting this issue!
I indeed forgot to mention that `~/.local/bin` should be added to `PATH`, since the command-line tools should be installed there:
```
$ ls ~/.local/bin/trezor-*
/home/roman/.local/bin/trezor-agent  
/home/roman/.local/bin/trezor-gpg	
/home/roman/.local/bin/trezor-gpg-agent
```

```
$ export PATH="$PATH:~/.local/bin/"
$ which trezor-gpg
/home/roman/.local/bin/trezor-gpg
```

**Comment by romanz** [comment]
https://github.com/pypa/pip/issues/3813
