### ISSUE TITLE
Documentation: Add Redhat/Fedora install instructions

### ISSUE THREAD

**Issue by Z819** [romanz/trezor-agent#124]
Packages I know are needed:

`systemd-devel`

Not sure, but probably:
```
python-devel
libusb-devel
```

**Comment by romanz** [comment]
Thanks for reporting this issue :)
I am current running Debian-based system, so I'll install Fedora in a VM and update the instructions.

**Comment by romanz** [comment]
Installation commands on Fedora 25: 
```
$ sudo yum update
$ sudo yum install python-pip python-devel libusb-devel libudev-devel \
                   gcc redhat-rpm-config
$ pip install --user trezor_agent
```
