### ISSUE TITLE
Setting up a secondary machine

### ISSUE THREAD

**Issue by jphastings** [romanz/trezor-agent#128]
The [guide](https://github.com/romanz/trezor-agent/blob/master/README-GPG.md) excellently explains how to create a new key on a new machine, but if my Ledger already has a GPG key on it from one machine, what commands should I use to set up a second machine to use the same key?

If you have the time to answer here I'd be happy to create  PR to update the Readme!

**Comment by romanz** [comment]
Thanks for opening this issue!
Just to make sure - are you asking about exporting the secret GPG key from the Ledger device to your PC?

**Comment by romanz** [comment]
@jphastings Ping :)

**Comment by romanz** [comment]
Please take a look at #88 - it might be relevant to your question (IIUC).

**Comment by jphastings** [comment]
Ugh, sorry; I completely missed your reply! Actually I'm more interested in extracting the _public_ key from the Ledger device (the set up process documented implies that each set up will create a brand new key, erasing the previous one; maybe I'm misinterpreting it?) Thanks!

**Comment by romanz** [comment]
No problem :)

Since the GPG key creation is using the current timestamp, in order to re-create the same public key you'll need to use the same timestamp.
I'll update the documentation with a screencast for this issue.

**Comment by romanz** [comment]
Please take a look at:
[![asciicast](https://asciinema.org/a/M4lRjEmGJ2RreQiHBGWT9pzp4.png)](https://asciinema.org/a/M4lRjEmGJ2RreQiHBGWT9pzp4)
