### ISSUE TITLE
trezor-agent usage in SSH config

### ISSUE THREAD

**Issue by pree** [romanz/trezor-agent#129]
Is it possible to use trezor-agent inside the ~/.ssh/config ?

I've setup host-aliases and would like to still use them, but with the trezor-agent.
Tried it with the ProxyCommand:
`ProxyCommand trezor-agent %r@%h -c`
`ProxyCommand trezor-agent %r@%h -- ssh %r@%h -p %p`
but it's not working, it just prints `-bash: line 1: $'SSH-2.0-OpenSSH_7.5\r': command not found`.

**Comment by romanz** [comment]
Thanks for suggesting this feature!
I'll take a look at it during the weekend :)

**Comment by vsund** [comment]
Definitely would appreciate this 👍

I configured everything in `.ssh/config` to be able to use a short `ssh hostname`. Would love to continue this :)

**Comment by romanz** [comment]
The `ProxyCommand` command is run by the `ssh` binary, so it cannot override the [SSH_AUTH_SOCK](https://stackoverflow.com/questions/22154423/how-is-ssh-auth-sock-setup-and-used-by-ssh-agent) environment variable used by `ssh` in order to connect to the `trezor-agent` tool (instead of the distro-provided `ssh-agent`).

**Comment by romanz** [comment]
However, I can suggest using a helper [bash script](https://gist.github.com/romanz/45b5cb033d15469a7527f8fe6d7d9cde) to provide similar funcionality:

```shell
#!/bin/bash
AGENT="trezor-agent"
HOST=$1
echo "Connecting to '${HOST}' using '${AGENT}'..." 1>&2
${AGENT} ${HOST} -- ssh $*
```
This way you can run `tssh user@host -v` and it will run the `ssh user@host -v`, using ssh-agent emulation provided by `trezor-agent user@host`.

What do you think?

**Comment by romanz** [comment]
Also, please take a look at https://github.com/romanz/trezor-agent/issues/75#issuecomment-258169714

**Comment by pree** [comment]
With the bash script you provied you would still have to type the user, host and port (when not default port) each time instead of an alias. The Script in #75 looks really promising, is that one available anywhere ?

**Comment by romanz** [comment]
I've actually implemented a bit different feature.
You can run `trezor-agent /path/to/config/trezor.pub -s`, where the file contains the SSH public keys. 
The tool will load all the public keys into its "ssh-agent" memory, so you can use all your `.ssh/config` aliases as usual:

```shell
$ trezor-agent foo >> /tmp/trezor.pub
$ trezor-agent bar >> /tmp/trezor.pub
$ trezor-agent /tmp/trezor.pub 
ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEh3g4cQde/M+cruqWLcJFvQHQceljCkEK/+d7gOVKbt1jp6AJpcfG9eXHl9Nv/ES00oGMF9f5eEbRezuUxBsEQ= <ssh://foo|nist256p1>
ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBE8JlDVQ6kpVEMO1CH8qCsDHWTvgTJ16IPBhhUXTirVBpBjJdgbySPTrZZKm+gAxyTnFCLhNsIv2ULFiI7In1AM= <ssh://bar|nist256p1>
$ trezor-agent /tmp/trezor.pub -s  # Spawns a subshell, using the SSH identities 
                                   # from the file above.
<subshell> $ ssh-add -L            # Note that all the public keys are already loaded.
ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEh3g4cQde/M+cruqWLcJFvQHQceljCkEK/+d7gOVKbt1jp6AJpcfG9eXHl9Nv/ES00oGMF9f5eEbRezuUxBsEQ= <ssh://foo|nist256p1>
ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBE8JlDVQ6kpVEMO1CH8qCsDHWTvgTJ16IPBhhUXTirVBpBjJdgbySPTrZZKm+gAxyTnFCLhNsIv2ULFiI7In1AM= <ssh://bar|nist256p1>
<subshell> $ ssh an_alias        # Should work if the host contains `foo` or `bar` 
                                 # SSH public key (from above).
```

**Comment by romanz** [comment]
> The Script in #75 looks really promising, is that one available anywhere ?
Thanks for the reminder, it would be a useful script :) 
#130

**Comment by vsund** [comment]
I think such a script wouldn't be that hard. It just needs to call `ssh $*` with a custom parameter `-i <temp_keyfile_path>` if I'm not mistaken :)

**Comment by romanz** [comment]
@vsund The problem with using `-i` flag is that the TREZOR cannot export the SSH private key to the PC, so I am using the [SSH agent protocol](https://tools.ietf.org/html/draft-miller-ssh-agent-00) to sign the challenge on the TREZOR device.

**Comment by romanz** [comment]
The issue will be tracked by #130

**Comment by slush0** [comment]
Wow, that subshell feature is killing it! I'm wondering why you don't promote it better in documentation. I found it just by chance here... The usage is not obvious from the help itself.

**Comment by romanz** [comment]
@slush0 Thanks a lot for the compliment and the heads-up!
Will update the documentation and the help string.
