### ISSUE TITLE
sudo pip install trezor_agent fails to compile

### ISSUE THREAD

**Issue by PavelNiedoba** [romanz/trezor-agent#131]
I assume trezor_agent is part of this repo, I'm trying to follow install guide

compilation.err.txt
tmp/comp.err

i asked question on https://stackoverflow.com/questions/45692279/using-bitcoin-trezors-ssh-agent too

**Comment by prusnak** [comment]
As mentioned here: https://github.com/trezor/python-trezor#install:

On Linux you might need to run these commands first:

```
sudo apt-get install python-dev cython libusb-1.0-0-dev libudev-dev git
sudo pip install setuptools
```

**Comment by PavelNiedoba** [comment]
this solved installation problem but running 

trezor-agent pavel@google.com 

failed  with 

```
Traceback (most recent call last):
  File "/usr/local/bin/trezor-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3049, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3033, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3062, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 660, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 673, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 858, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'urllib3<1.23,>=1.21.1' distribution was not found and is required by requests
```

**Comment by romanz** [comment]
Thanks for reporting this issue!

**Comment by romanz** [comment]
@PavelNiedoba 
Could you please try to update `urllib3` using `pip install --upgrade urllib3`?

**Comment by PavelNiedoba** [comment]
OK, sorry for late reply. I got this working on latest Linux Mint (18). It's quite nice, but I'm using Chrome password manager extension which stops working once I use agent. I have to disconnect and reconnect the device to get PM working again. Is this feature or bug ?

**Comment by romanz** [comment]
It seems that opening a connection to the TREZOR using the Python library indeed causes the password manager to lose the connection to the device. This actually happens for the Web wallet as well.
This can be reproduced by running `trezorctl ping msg` from the command-line...

Maybe you can use [TREZOR bridge](https://doc.satoshilabs.com/trezor-user/download.html#trezor-bridge) to access the device from Python and Chrome simultaneously (see [PR](https://github.com/romanz/trezor-agent/pull/109))?
