### ISSUE TITLE
Idea: Graphical pinentry for Trezor?

### ISSUE THREAD

**Issue by jb55** [romanz/trezor-agent#135]
I was thinking about ways to make trezor-gpg-agent a bit nicer from an OS packaging standpoint.

* **Goal**: a trezor-gpg-agent system service that runs in the background when a user logs in.

* **Issue**: I noticed the console pinentry prompt sometimes appears in the trezor-gpg-agent tty if it's not unlocked. Ideally it would prompt a graphical pinentry (specialized for trezor?)

* **Q**: do we need to create a new x11/qt/gtk pinentry app for trezor or is there some general trezor-like graphical pinentry available?

* Maybe some way to prompt a standalone graphical pinentry program from trezor-gpg-agent when there's a display?

Anyone have any ideas on the best way to approach this or other comments?

**Comment by romanz** [comment]
Thanks for the suggestion!
Regarding graphical pinentry: I've added a simple Qt-based dialog box prompt when the agent has no tty at  https://github.com/romanz/trezor-agent/commit/f6911a00163e092396e529440883e9fa70374358.
Please give it a try to see if this can be used for your idea.
Let me know if there is any issue/question/problem :)

**Comment by jb55** [comment]
Thanks! I was able to create a system service on NixOS for trezor-gpg-agent. https://github.com/NixOS/nixpkgs/pull/29831

**Comment by romanz** [comment]
Cool, thanks for the integration with NixOS!
I'll release a new version of trezor_agent package to PyPI tomorrow :)

**Comment by jb55** [comment]
> I'll release a new version of trezor_agent package to PyPI tomorrow :)

Great, thanks! That might help get it merged.

**Comment by romanz** [comment]
I've updated the core [libagent](https://pypi.python.org/pypi/libagent/0.9.3) package at PyPI.
Note that the [TREZOR-specific](https://pypi.python.org/pypi/trezor_agent) wrapper [depends](https://github.com/romanz/trezor-agent/blob/master/agents/trezor/setup.py#L13) on it - so it should be installed automatically when using `pip`:

```
$ pip install trezor_agent
Collecting trezor_agent
  Downloading trezor_agent-0.9.0.tar.gz
Collecting libagent>=0.9.0 (from trezor_agent)
  Downloading libagent-0.9.3.tar.gz (890kB)
    100% |████████████████████████████████| 890kB 1.2MB/s 
...
```
