### ISSUE TITLE
Trouble getting trezor-gpg working on MacOS

### ISSUE THREAD

**Issue by romanz** [romanz/trezor-agent#136]
(copied from [reddit](https://www.reddit.com/r/TREZOR/comments/6yt8kz/trouble_getting_trezorgpg_working_on_macos/))

I've got trezor_agent working with mosh/ssh, when I try it with gpg (after replacing all the "gpg2" strings with "gpg" because that's what brew calls it) I get the following:

```
Traceback (most recent call last):
  File "/usr/local/bin/trezor-gpg", line 11, in <module>
    load_entry_point('trezor-agent==0.9.0', 'console_scripts', 'trezor-gpg')()
  File "/usr/local/bin/trezor_agent.py", line 6, in <lambda>
    gpg_tool = lambda: libagent.gpg.main(DeviceType)
  File "/Library/Python/2.7/site-packages/libagent/gpg/__init__.py", line 149, in main
    return args.func(device_type=device_type, args=args)
  File "/Library/Python/2.7/site-packages/libagent/gpg/__init__.py", line 86, in run_create
    existing_gpg = keyring.gpg_version().decode('ascii')
  File "/Library/Python/2.7/site-packages/libagent/gpg/keyring.py", line 199, in gpg_version
    output = sp.check_output(args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in     _execute_child
  raise child_exceptionOSError: [Errno 2] No such file or directory
```

**Comment by romanz** [comment]
Could you please run  `gpg --version` on your machine (since trezor-agent works only with GnuPG v2.1+)?

**Comment by mnemnion** [comment]
Sure thing! (original reporter checking in):

```
gpg (GnuPG) 2.2.0
libgcrypt 1.8.1
```

**Comment by romanz** [comment]
Thanks!
It seems that the [latest GnuPG](https://lists.gnupg.org/pipermail/gnupg-announce/2017q3/000413.html) (2.2.0) is now installed as `/usr/bin/gpg` (and not `/usr/bin/gpg2`).
So the issue can be reproduced on Arch linux as well :)

**Comment by romanz** [comment]
When running `fake-device-gpg-agent` fails (not finding `gpg2`), it says:
```
Traceback (most recent call last):
  File "/home/test/.local/bin/fake-device-gpg-agent", line 11, in <module>
    load_entry_point('fake-device-agent', 'console_scripts', 'fake-device-gpg-agent')()
  File "/home/test/trezor-agent/agents/fake/fake_device_agent.py", line 7, in <lambda>
    gpg_agent = lambda: libagent.gpg.run_agent(DeviceType)
  File "/home/test/trezor-agent/libagent/gpg/__init__.py", line 118, in run_agent
    handler = agent.Handler(device=device_type())
  File "/home/test/trezor-agent/libagent/gpg/agent.py", line 79, in __init__
    self.pubkey_bytes = keyring.export_public_keys()
  File "/home/test/trezor-agent/libagent/gpg/keyring.py", line 217, in export_public_keys
    return sp.check_output(args=args)
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1333, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'gpg2'
```

**Comment by romanz** [comment]
Could you please check `/Library/Python/2.7/site-packages/libagent/gpg/keyring.py` file, to see that it uses the correct GPG binary (at `gpg_command()` function)?

**Comment by romanz** [comment]
BTW, you can test the library using "fake-device" implementation (which doesn't require hardware device for signature and decryption - which should be used ONLY for tests):

```bash
$ DEVICE=fake-device ./scripts/gpg-init "John Doe <john@doe.bit>"
$ export GNUPGHOME=~/.gnupg/fake-device
$ fake-device-gpg-agent &
$ echo 123 | gpg --sign -a | gpg --verify -v
```

**Comment by romanz** [comment]
@mnemnion 
Could you please add a `gpg2` symlink to `/usr/bin/gpg` - just to see if there are any other issues?
(using `sudo ln -s /usr/bin/gpg /usr/bin/gpg2` command)

**Comment by mnemnion** [comment]
Yep, `/Library/Python/2.7/site-packages/libagent/gpg/keyring.py` wants `gpg2` (line 182). I'll try the symlink next.

**Comment by mnemnion** [comment]
`brew` uses `/usr/local/bin/` so I've issued `sudo ln -s /usr/local/bin/gpg /usr/local/bin/gpg2` (the sudo is probably superfluous here). 

The line `pip install --user -e ./agents/fake` executes successfully but `DEVICE=fake-device ./scripts/gpg-init "John Doe <john@doe.bit>"` fails with 

```
./scripts/gpg-init: line 18: fake-device-gpg: command not found
```

**Comment by mnemnion** [comment]
However running the usual `DEVICE=trezor ./scripts/gpg-init "John Doe <john@doe.bit>"` with the trezor plugged in seems to work. I cancelled on the device since I don't need a John Doe key.

**Comment by mnemnion** [comment]
Note that I did a `git reset --hard HEAD` to get rid of my local changes and it still seems to work.

Not sure what the issue was with the fake device but with the real device the symlink seems to fix it!

**Comment by romanz** [comment]
Sounds great :)

**Comment by romanz** [comment]
Regarding the "fake-device-gpg: command not found" error: usually `pip install --user` puts the `fake-device-gpg` script under `/home/$USER/.local/bin/fake-device-gpg`, so this error may happen if your PATH doesn't contain `~/.local/bin`.

**Comment by mnemnion** [comment]
For the sake of anyone who might find this later: I ran `pip -v install --user -e ./agents/fake` and the `-v` option showed that on macOS the correct path is `/Users/$USER/Library/Python/2.7/bin`. 

Adding this to my $PATH makes the fake-device script work correctly.

Thanks for all your help @romanz!

**Comment by romanz** [comment]
You're welcome :)
