### ISSUE TITLE
Docs: idea to write how to use GPG with Thunderbird/Enigmail

### ISSUE THREAD

**Issue by galuszkak** [romanz/trezor-agent#142]
Hi,

I'm trying to figure how to use Enigmail with GPG with my trezor but this seems to me a little confusing. Could someone help me understand how to do it? I can later write documentation for that.

Thanks
Kamil

**Comment by romanz** [comment]
Thanks for the suggestion, will do :)

**Comment by romanz** [comment]
![01](https://user-images.githubusercontent.com/9900/31327339-47a5f69a-acd7-11e7-997c-7b5a286fe5bc.png)
![02](https://user-images.githubusercontent.com/9900/31327344-51dcd246-acd7-11e7-8cdc-dd305a512dbb.png)
![03](https://user-images.githubusercontent.com/9900/31327346-546862a0-acd7-11e7-8e00-b40994bd6f17.png)
![04](https://user-images.githubusercontent.com/9900/31327356-660d098e-acd7-11e7-9e43-762898f5b57e.png)
![05](https://user-images.githubusercontent.com/9900/31327365-76679dda-acd7-11e7-9403-6965f0c6d8fe.png)
![06](https://user-images.githubusercontent.com/9900/31327371-7c1da4cc-acd7-11e7-9a5a-20accf621b49.png)

**Comment by romanz** [comment]
Please take a look at https://github.com/romanz/trezor-agent/blob/master/doc/enigmail.md :)

**Comment by galuszkak** [comment]
Looks nice @romanz . 

There is one thing that actually bugs me in README-GPG.md . You can't init your GPG key env without using /scripts/gpg-init which isn't included in PyPI package. If you want to use it you have to never the less download the repo or script only and then use it.

**Comment by AgentME** [comment]
Yeah I found it surprising that `trezor-gpg create` (accessible from the pypi package) didn't do the same thing as /scripts/gpg-init. I tried using it first just thinking the documentation hadn't been updated to use the pypi-accessible commands.

**Comment by romanz** [comment]
Oops... you're right, I totally forgot about the fact that `gpg-init` is not part of the official distribution.
I'll rewrite this Bash script in Python, and add it to the relevant PyPI packages.
