### ISSUE TITLE
GPA instructions not working

### ISSUE THREAD

**Issue by andrevmatos** [romanz/trezor-agent#144]
On current master (e4fdca0), using python3 and local user installation, I can sign and decrypt from command line (gpg v.2.2.1), but firing `gpa` as per docs, it gets stuck and doesn't load.
With the normal setup (localfile gnupg privatekey), it loads all public and private keys as usual.
[Here are the logs](https://github.com/romanz/trezor-agent/files/1369465/gpg-agent.log) of a session where, with agent initially not loaded, `GNUPGHOME=~/.gnupg/trezor`, I first made a sign test (`echo 123 | gpg2 --sign | gpg2 --verify`) as the docs, which did succeed, and then, on same terminal, tried launching `gpa`. No logs on stdout/err from gpa.
Kgpg also doesn't load, giving lots of `gpg: can't connect to the agent: IPC connect call failed` errors, but I suppose that should be a new issue.

**Comment by romanz** [comment]
Thanks for reporting this issue!

It seems that my library does not support the `NOP` command:
```
2017-10-09 15:18:23,554 DEBUG        -> b'NOP'                                                                                            [keyring.py:59]
2017-10-09 15:18:23,554 ERROR        unknown request: b'NOP'                                                                              [agent.py:198]
```

**Comment by romanz** [comment]
This seems to fix the issue...

**Comment by andrevmatos** [comment]
Yeah, 1ef96be fixed it! Gpa working again flawlessly. Thank you very much.

**Comment by romanz** [comment]
You're welcome :)
