### ISSUE TITLE
Keys created with scripts/gpg-init are marked as not supporting compression or MDC

### ISSUE THREAD

**Issue by AgentME** [romanz/trezor-agent#145]
While encrypting some files to a new trezor key, I noticed the encrypted output files were much bigger than some encrypted output files that were encrypted for a different non-trezor key. Every gpg key has a list of preferences about supported features, and it seems like the keys generated by trezor-agent have a very barebones preference list, lacking any compression algorithms or the MDC (modification detection code) feature. I edited an existing key of mine to have gpg's default preferences, and everything worked fine (I figure it's because everything but the asymmetric algorithm is run in gpg and not the trezor, so gpg's own defaults are good).

Preferences of a Trezor-generated key:

```
     Cipher: AES256, 3DES
     Digest: SHA256, SHA1
     Compression: Uncompressed
     Features: Keyserver no-modify
```

Default gpg (2.1.11) preferences:

```
     Cipher: AES256, AES192, AES, 3DES
     Digest: SHA256, SHA384, SHA512, SHA224, SHA1
     Compression: ZLIB, BZIP2, ZIP, Uncompressed
     Features: MDC, Keyserver no-modify
```

I think trezor-generated keys ought to at least have the compression and mdc prefs at least, but the extra stronger digest modes would be nice too.

(Some notes for someone looking into this or a user wanting to update a key of theirs: a gpg key's preferences may be viewed by using `gpg --edit-key keyid` followed by the `showpref` command. A key's preferences may be set to gpg's defaults with the `setpref` command.)

**Comment by romanz** [comment]
Thanks for reporting this issue!
I'll update the key generation code soon :)

**Comment by romanz** [comment]
```bash
$ gpg2 --edit-key roman.zeyde

gpg> showpref
[ultimate] (1). Roman Zeyde <roman.zeyde@gmail.com>
     Cipher: AES256, 3DES
     Digest: SHA512, SHA384, SHA256, SHA1
     Compression: ZLIB, BZIP2, ZIP, Uncompressed
     Features: MDC, Keyserver no-modify


```

**Comment by romanz** [comment]
@AgentME 
Please take a look :)

**Comment by AgentME** [comment]
Looks good! Thanks!

**Comment by AgentME** [comment]
Though actually I think it'd make sense to prioritize SHA256 over the other digest methods like gpg usually does: they're kinda over-paranoid and take up more space.

**Comment by romanz** [comment]
You're right - fixed at https://github.com/romanz/trezor-agent/pull/146/commits/c8ed4a223a6673c0617271c4c6bed8fcd1bfeb6f#diff-3917845cdbb968e7e9bc3d6a61c65de3R26.
