### ISSUE TITLE
Add documentation for adding TREZOR-based GPG subkey

### ISSUE THREAD

**Issue by romanz** [romanz/trezor-agent#147]
Following https://github.com/romanz/trezor-agent/issues/49#issuecomment-335249089.

**Comment by romanz** [comment]
[![asciicast](https://asciinema.org/a/JFazcJfORrz7k9DmVXknaXBfD.png)](https://asciinema.org/a/JFazcJfORrz7k9DmVXknaXBfD)

**Comment by romanz** [comment]
@andrevmatos
Please take a look (https://github.com/romanz/trezor-agent/commit/835f283ccffe3515155f7c69bb52db605b327c68)

**Comment by andrevmatos** [comment]
Great! It worked here. Thank you!
Does this subkey creation also depends on timestamp (for future re-creation)? Is it possible to create sub-UIDs with it?

**Comment by romanz** [comment]
> Does this subkey creation also depends on timestamp (for future re-creation)? 
Yes, it is - and you can override it using TIMESTAMP environment variable.

> Is it possible to create sub-UIDs with it?
No, IIUC currently the primary key is used for adding UIDs (e.g. certification).
The TREZOR-based subkeys are used for signatures and encryption.

**Comment by andrevmatos** [comment]
Right.. if it's not asking too much, can you provide a command line for adding a UID to the primary key with trezor-agent?

**Comment by andrevmatos** [comment]
Ok, I thought it had a different process, but trezor only needs to sign a simple operation to add a new uid:
For records, one can add a new UID with:
```
gpg --edit-key <primary-uid>
adduid
<fill information, confirm sign on trezor>
uid <number_of_new_uid>
trust
<set trust to 5=ultimate>
save
```

**Comment by romanz** [comment]
> can you provide a command line for adding a UID to the primary key with trezor-agent?

No problem, will do in a separate PR.

**Comment by romanz** [comment]
Merged in master (https://github.com/romanz/trezor-agent/commit/0999a85529156a5aa5e2ae3bca64b2b6adc81ac6)
