### ISSUE TITLE
ED25519 PublicKey Generation on Ledger Nano S Stalling

### ISSUE THREAD

**Issue by StaceC** [romanz/trezor-agent#149]
Hi, using:

- [Ledger SSH Agent](https://github.com/LedgerHQ/blue-app-ssh-agent/tree/master) on master running on a Nano S
- Trezor Agent on master running on Ubuntu 14.04.5 Trusty Tahr

Running the Quick Start Identity Creation command works fine. When I try and run it with CURVE=ed25519 I see the following:

- Run `DEVICE=ledger CURVE=ed25519 ./scripts/gpg-init "John Doe <johnd@acme.com>"`
- 'Provide public key?' shown on Nano S
- Press 'yes' button TWICE on Nano S
- Get output `please confirm GPG signature on LedgerNanoS for "<gpg://John Doe <johnd@acme.com>|ed25519>"...`
- Pressing 'yes' button repeatedly does nothing
- Press 'no' and get a Traceback ending with `ledgerblue.commException.CommException: Exception : Invalid status 6985`

https://asciinema.org/a/oJDKMRr6jKJKkNvkb0AyLwmci

I know you've mentioned the GPG code is still in development, but wondering if this is an issue you've seen, or if it has to do with my setup.

Thanks,

Stace

**Comment by romanz** [comment]
This reproduces on my Ledger device as well - exactly as you described.

**Comment by romanz** [comment]
Thanks a lot for reporting this issue!
I'll take a look on it in the following days.

**Comment by romanz** [comment]
Can confirm that this happens on my Ledger Nano S device as well (running firmware v1.3.1 and SSH/PGP Agent v0.0.3).

**Comment by romanz** [comment]
Note that the `ledger-agent` tool works with ed25519 SSH keys (using almost the same client-side code as the the GPG tool):
```bash
$ ledger-agent -e ed25519 localhost >> ~/.ssh/authorized_keys 
$ ledger-agent -e ed25519 localhost -cv
2017-10-11 21:00:00,373 INFO         identity #0: <ssh://localhost|ed25519>                                                               [__init__.py:208]
2017-10-11 21:00:00,380 INFO         running ['ssh', 'localhost'] with {'SSH_AUTH_SOCK': '/tmp/trezor-ssh-agent-n4q6f1xh', 'SSH_AGENT_PID': '18410'} [server.py:119]
2017-10-11 21:00:01,892 INFO         please confirm user "roman" login to "<ssh://localhost|ed25519>" using LedgerNanoS...                [client.py:46]
2017-10-11 21:00:03,063 INFO         signature status: OK                                                                                 [protocol.py:151]
Welcome to Linux Mint 18.2 Sonya (GNU/Linux 4.10.0-37-generic x86_64)

 * Documentation:  https://www.linuxmint.com
Last login: Fri Sep 22 14:10:37 2017 from 127.0.0.1
0 ~ $ logout
Connection to localhost closed.
```

**Comment by romanz** [comment]
The APDUs sent during the session can be seen below:
[![asciicast](https://asciinema.org/a/JZBeyqo2jAMu31noKxdZSkjpO.png)](https://asciinema.org/a/JZBeyqo2jAMu31noKxdZSkjpO)

@btchip
Could you please take a look at this issue?

**Comment by romanz** [comment]
P.S.
Actually, I don't remember that I successfully created ed25519-based GnuPG identity using the Ledger Nano S...

**Comment by btchip** [comment]
Yes, it might work for signing but not for encryption. Need to review this later

**Comment by romanz** [comment]
Thanks for the help!

**Comment by StaceC** [comment]
Hi, thanks for replicating that so quickly @romanz 
I'll take a look at the ledger-agent SSH

**Comment by StaceC** [comment]
Turns out Ledger Nano S ed25519 derivation does not support non-hardened addresses. I was using them to test, e.g. 44'/225'/0'/0/0 (note the last two nodes are not hardened).

See - [here](https://www.reddit.com/r/ledgerwallet/comments/71tphi/is_there_a_javascript_implementation_of_os_perso/) for more details.

Currently, there is no requirement from our side to use non-hardened address derivation, therefore I am happy to close this issue.

Many thanks @btchip and @romanz for your support.
