### ISSUE TITLE
can't find cli osx macOS Sierra, nothing in ~/.local/bin PATH

### ISSUE THREAD

**Issue by codeHatcher** [romanz/trezor-agent#155]
did `pip install --user trezor_agent` and then tried to run command line utility but it shows not found I see there is information on adding `~/.local/` to the PATH but there is nothing in that directory for me. I have a screenshot below with the summary

![image](https://user-images.githubusercontent.com/5360982/31639036-b13984fa-b2a4-11e7-8ab9-b60f1f745986.png)

**Comment by romanz** [comment]
Following https://github.com/romanz/trezor-agent/issues/136#issuecomment-328303916, it may be installed under `/Users/$USER/Library/Python/2.7/bin`.

**Comment by codeHatcher** [comment]
that was it, ty!

**Comment by codeHatcher** [comment]
@romanz added a little info to the install of the README for the next person that comes across this issue

**Comment by romanz** [comment]
Thanks again :)
