### ISSUE TITLE
Why is this (trezor-agent) needed, why is Trezor not compatible with gpg-agent?

### ISSUE THREAD

**Issue by nurupo** [romanz/trezor-agent#160]
I'm looking into hardware keys and Trezor looks interesting. The thing I don't understand is why `trezor-agent` is needed? YubiKey can be used without any custom agent, just with the stock `gpg-agent`. Do you know if there are any plans of making Trezor work with `gpg-agent` or upstreaming any special support for Trezor into `gpg-agent`?

**Comment by romanz** [comment]
The main reason is that standard OpenPGP smart card support (see the full spec [here](https://gnupg.org/ftp/specs/OpenPGP-smart-card-application-3.3.1.pdf)) requires more complexity on the device side - and I preferred to keep the embedded C code as simple as possible.

Saying that, I remember that there was an effort by @saleemrashid to implement the OpenPGP smart card protocol for the TREZOR device, but I am not sure about its current status.

**Comment by saleemrashid** [comment]
Current status: lack of time to work on it, unfortunately.

**Comment by romanz** [comment]
BTW, this feature may be relevant for [TREZOR T](https://blog.trezor.io/pre-order-your-new-trezor-model-t-cf2a3426cf03).
