### ISSUE TITLE
Can trezor-agent handle multiple identities?

### ISSUE THREAD

**Issue by edivad13** [romanz/trezor-agent#161]
What happens if I issue another trezor gpg init with a different email? The previus identity get discarded?

**Comment by edivad13** [comment]
Solved: https://github.com/romanz/trezor-agent/issues/88

I haven't done a proper backlog (newbie here)

trezor-agent uses timestamp, so you can have multiple identities

**Comment by edivad13** [comment]
And i would just like to add a juicy detail: https://github.com/romanz/trezor-agent/issues/91

> You can now set the passphrase using TREZOR_PASSPHRASE environment variable.

Basically aside of having multiple identities based on the timestamp, you can also have hidden identities!

**Comment by Ranguna** [comment]
Sorry for the necro comment, but for anyone finding this issue and find the "explanation" above unclear, here's how I'm doing this:

If you run the following for the first time:
```
trezor-gpg init foobar
```

By default, it will create a new folder inside `$HOME/.gnupg/`. If you rerun the above again (even with a different identity name), the command will complain about the folder already existing. Thus, to have multiple identities, all you need to do it change the home folder:

```
trezor-gpg init foobar2 --homedir $HOME/.gnupg/foobar2
```

And set `GNUPGHOME` based on your needs.
