### ISSUE TITLE
TREZOR_PASSPHRASE enviroment variable doesn't work in certain conditions

### ISSUE THREAD

**Issue by edivad13** [romanz/trezor-agent#163]
It seems that if the trezor passphrase option is not marked on https://wallet.trezor.io/, trezor-gpg simply ignores the variable

**Comment by romanz** [comment]
You're right - but the decision happens at the device itself - if the device has no passphrase protection enabled, it [won't ask](https://github.com/trezor/trezor-mcu/blob/892bb8501a1282535a9c721d0a3187f51aa5585b/firmware/protect.c#L237-L239) the user to provide one.
