### ISSUE TITLE
trezor-gpg init with TREZOR_PASSPHRASE doesn't work 

### ISSUE THREAD

**Issue by edivad13** [romanz/trezor-agent#164]
Procedure:
```
$ export TREZOR_PASSPHRASE=123
$ trezor-gpg init myemail@email.com
$ gpg2 --list-keys  # regularly outputs my brand new GPG key
```

then if i use the test command `echo 12 | gpg2 --sign`, the output is the following:

```
gpg: Warning: not using 'myemail@email.com' as default key: No secret key
gpg: all values passed to '--default-key' ignored
gpg: no default secret key: No secret key
gpg: signing failed: No secret key
```

**Comment by romanz** [comment]
Good catch!
I'll change passphrase entry to use a UI-based dialog box (same as used for PIN entry).

**Comment by edivad13** [comment]
Thanks! But currently also the pin entry is all displayed on the terminal in my case

**Comment by romanz** [comment]
> But currently also the pin entry is all displayed on the terminal in my case

You're right - but this happens only when a terminal is available.
Usually `trezor-gpg-agent` is invoked in the background (by `gpg`) so it needs to use UI-based PIN entry.

**Comment by edivad13** [comment]
Man, updated and its working flawlessy with secret identities. You are my hero

**Comment by romanz** [comment]
Thanks :)
