### ISSUE TITLE
Set default curve

### ISSUE THREAD

**Issue by smarek** [romanz/trezor-agent#175]
Hi, is it possible to set for various utilities (trezor-agent, trezor-gpg, ...) default curve to ED25519 instead of NIST256p1 ?

I mean something more elegant than using various helper scripts, shell command aliases, etc...

If this will become planned feature, could the solution be based on configuration in usual places, such as `.ssh/config` and `.gnupg/trezor/gpg.conf` ?

**Comment by romanz** [comment]
Thanks for the suggestion!
I would add config file support to `trezor-agent` - to override command-line parameters' default values.

**Comment by romanz** [comment]
https://github.com/romanz/trezor-agent/commit/0d059587a734a2c6c89cbb28ffd8b061a1512f7e adds config file support for SSH.

**Comment by smarek** [comment]
Thank you, what is an example config file, we can use now?

**Comment by romanz** [comment]
You're welcome :)

`configargparse` uses `.ini` format for the [configuration file](https://github.com/bw2/ConfigArgParse#example), so `--param=value` flags should be written as:
```
param = value
```

For example, I am currently using the following configuration file:
```
$ cat ~/.ssh/agent.config 
ecdsa-curve-name = ed25519
```
