### ISSUE TITLE
Lost all my keys after update, how to add many keys ?

### ISSUE THREAD

**Issue by sp4ke** [romanz/trezor-agent#177]
After update, tried trezor-gpg init and it removed all the keys I had before. I made sure to save the creation time to regenerate them but now I cannot add more than one identity, every time I run init it resets the previous keys.

Looking at this function https://github.com/romanz/trezor-agent/blob/f57dbb553f4424f81d793140e43b2c8abc8b71d5/libagent/gpg/__init__.py#L79  why was `run_create` removed ? 

Can I make a PR to offer `run_create` it as an other option to the script  ?

**Comment by romanz** [comment]
`run_create` is replaced by `run_init`: https://github.com/romanz/trezor-agent/blob/13cd6be2d15911765cf336fa560215922090e016/libagent/gpg/__init__.py#L113

After you run `trezor-gpg init "Foo Bar"`, you can add more identities using:
```!sh
$ trezor-gpg init "Foobar" -vv
$ export GNUPGHOME=${HOME}/.gnupg/trezor
$ gpg2 -K
/home/roman/.gnupg/trezor/pubring.kbx
------------------------------------------
sec   nistp256/6275E7DA 2017-12-05 [SC]
uid         [ultimate] Foobar
ssb   nistp256/35F58F26 2017-12-05 [E]

$ gpg2 --edit Foobar
gpg> adduid
Real name: Blahh
Email address: 
Comment: 
You selected this USER-ID:
    "Blahh"

Change (N)ame, (C)omment, (E)mail or (O)kay/(Q)uit? o

gpg> save

$ gpg2 -K
/home/roman/.gnupg/fake-device/pubring.kbx
------------------------------------------
sec   nistp256/6275E7DA 2017-12-05 [SC]
uid         [ultimate] Blahh
uid         [ultimate] Foobar
ssb   nistp256/35F58F26 2017-12-05 [E]
```

**Comment by sp4ke** [comment]
Thanks @romanz for the answer. I think it should be stated in the gpg instructions somewhere.

**Comment by romanz** [comment]
You're welcome :)
