### ISSUE TITLE
gpg encryption fails with Curve25519

### ISSUE THREAD

**Issue by btchip** [romanz/trezor-agent#18]
gpg encryption seems to fail because compressed keys are not handled for that scheme. It could be interesting to test with non compressed keys, I didn't try that yet.

**Comment by romanz** [comment]
Thanks for finding and reporting this bug :)
I haven't tried to use Curve25519 keys for encryption yet, so I'd try to reproduce this issue and see how it could be solved.

**Comment by romanz** [comment]
Curve25519 key generation: http://www.gniibe.org/memo/software/gpg/keygen-25519.html

```
$ gpg2 --export | gpg2 --list-packets --verbose
# off=0 ctb=98 tag=6 hlen=2 plen=51
:public key packet:
	version 4, algo 22, created 1470166270, expires 0
	pkey[0]: 092B06010401DA470F01 ed25519 (1.3.6.1.4.1.11591.15.1)
	pkey[1]: 40025BAD045D9FB7A7418A5383EA32CB860D52617297D3B122A7DC28CCA4E3AFF5
	keyid: 6C8FD65EF91A2A3A
# off=53 ctb=b4 tag=13 hlen=2 plen=7
:user ID packet: "testing"
# off=62 ctb=88 tag=2 hlen=2 plen=121
:signature packet: algo 22, keyid 6C8FD65EF91A2A3A
	version 4, created 1470166270, md5len 0, sigclass 0x13
	digest algo 8, begin of digest 9e 9c
	hashed subpkt 2 len 4 (sig created 2016-08-02)
	hashed subpkt 27 len 1 (key flags: 03)
	hashed subpkt 11 len 4 (pref-sym-algos: 9 8 7 2)
	hashed subpkt 21 len 5 (pref-hash-algos: 8 9 10 11 2)
	hashed subpkt 22 len 3 (pref-zip-algos: 2 3 1)
	hashed subpkt 30 len 1 (features: 01)
	hashed subpkt 23 len 1 (keyserver preferences: 80)
	subpkt 16 len 8 (issuer key ID 6C8FD65EF91A2A3A)
	data: CFEEE1BF5A54B47B56FABA26CF6DC887410A7CB476ABC523133B6B9EDCE6665C
	data: 1C083B84739F123098B6B1FC92D30F60A9F0D28971AD46BFDAFDA1CF8708F400
# off=185 ctb=b8 tag=14 hlen=2 plen=56
:public sub key packet:
	version 4, algo 18, created 1470166270, expires 0
	pkey[0]: 0A2B060104019755010501 cv25519 (1.3.6.1.4.1.3029.1.5.1)
	pkey[1]: 40168B8EDAC478227B53FD45E1080F7B2CEEC1DB77C89FEDF6F7FFF1900811085F
	pkey[2]: 03010807
	keyid: 0F652575642B0530
# off=243 ctb=88 tag=2 hlen=2 plen=97
:signature packet: algo 22, keyid 6C8FD65EF91A2A3A
	version 4, created 1470166270, md5len 0, sigclass 0x18
	digest algo 8, begin of digest 9e f6
	hashed subpkt 2 len 4 (sig created 2016-08-02)
	hashed subpkt 27 len 1 (key flags: 0C)
	subpkt 16 len 8 (issuer key ID 6C8FD65EF91A2A3A)
	data: 9976E6D5F322B948FAD431949F80992FA5F7A339484293379BB55C1E5EAD3D6F
	data: 15D37B4658F605B344EB514E666486F601214A995B47E4E912D3F7F7D9F26604
```

**Comment by romanz** [comment]
Curve25519-based ECDH works with GPG [2.1.7+](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=commit;h=e5891a82c39997b65ce9ff90eb6120db7bedd399).

**Comment by romanz** [comment]
`ed25519-donna` seems to have the needed [piece](https://github.com/floodyberry/ed25519-donna/blob/master/ed25519.c#L125) for implementing ECDH.

**Comment by romanz** [comment]
[curve25519-donna](https://github.com/agl/curve25519-donna) ECDH implementation may be useful for the TREZOR (since it's currently using [ed25519-donna](https://github.com/floodyberry/ed25519-donna) for signatures).

**Comment by essank** [comment]
it's look interesting, can I help you with it?

**Comment by romanz** [comment]
Gladly :)
Are you familiar with GPG implementation of Curve25519?
If so, I'd be happy to get some help with re-creating its functionality using Python module from https://github.com/agl/curve25519-donna/tree/master/python-src/curve25519?

**Comment by romanz** [comment]
Curve25519 ECDH is using Montgomery ladder: https://git.gnupg.org/cgi-bin/gitweb.cgi?p=libgcrypt.git;a=blob;f=mpi/ec.c;h=26dd94788102eff35c27e82292a0485a18339cbe;hb=f8241874971478bdcd2bc2082d901d05db7b256d#l1304.

**Comment by romanz** [comment]
Also, add Curve25519 keygrip computation (from https://git.gnupg.org/cgi-bin/gitweb.cgi?p=libgcrypt.git;a=blob;f=cipher/pubkey.c;h=8ec15fd410e91a21963a145189f02bbbbc16af9b;hb=HEAD#l618)

**Comment by romanz** [comment]
It should work now, with the latest TREZOR firmware version (https://github.com/trezor/trezor-mcu/pull/120) and the latest `trezor-agent` (https://github.com/romanz/trezor-agent/pull/51)
