### ISSUE TITLE
Using SSH - clarification on recovery process

### ISSUE THREAD

**Issue by AlexanderSupersloth** [romanz/trezor-agent#184]
I am a little confused on how some of this works and hope you can help me.

Suppose I used ledger-agent to create SSH logins for 5 different servers and I then lose my Ledger and have to recover it from the seed. Could I then login to any of my servers using `ledger-agent user@ssh.hostname.com -v -c` without having to generate a new public key?

I suppose I am just uncertain about whether anything is written to the device during public key generation? Do all of the unique public keys relate to a single unchanging private key?

**Comment by romanz** [comment]
> Could I then login to any of my servers using `ledger-agent user@ssh.hostname.com -v -c` without having to generate a new public key?

Yes, the SSH identity is generated from the seed and the `user@ssh.hostname.com` string.

> whether anything is written to the device during public key generation? 

No - the derivation result is stored in the device's volatile memory.

> Do all of the unique public keys relate to a single unchanging private key?

Each SSH identity is generated by a separate derivation from the seed, creating a separate public key (which is exported) and private key (never leaves the device and is used to authorize the connection).

**Comment by AlexanderSupersloth** [comment]
Thank you very much for your reply. I had not found the design document, but it was exactly what I needed. I understand how this works now.

**Comment by romanz** [comment]
You're welcome :)
