### ISSUE TITLE
Project name sounds like only Trezor is supported

### ISSUE THREAD

**Issue by eli-b** [romanz/trezor-agent#189]
Project name sounds like only Trezor is supported, even though Ledger and KeepKey agents are also available.
Additionally, the project's GitHub description only mentions Trezor.

**Comment by romanz** [comment]
(Sorry for the delayed response...)

I kept the GitHub project name mainly to prevent old URLs from breaking, but I did [split](https://github.com/romanz/trezor-agent/issues/101) the PyPI package names ([libagent](https://pypi.python.org/pypi/libagent) for the common code, and various "agents" for the specific devices' scripts).
