### ISSUE TITLE
agent fails in non default GPG home directory

### ISSUE THREAD

**Issue by btchip** [romanz/trezor-agent#19]
The agent won't find keys in a non default directory when it pipes gpg2 in keyring.py 

Maybe --homedir could be passed along with the socket to listen to when starting the agent

**Comment by romanz** [comment]
Thanks for finding this bug :)
Will take a look on this during the weekend.

**Comment by romanz** [comment]
BTW, could you please try setting GNUPGHOME environment variable to see if it helps?
According to the man page, it could be used to override the default home directory...

**Comment by btchip** [comment]
tried it, it doesn't seem to pass along the environment when spawning from the agent.

**Comment by romanz** [comment]
You're right - I will pass `--homedir` to the gpg binary.
