### ISSUE TITLE
Ubuntu - no graphical pinentry

### ISSUE THREAD

**Issue by pruflyos** [romanz/trezor-agent#194]
Ubuntu 16.04 and 17.10

Although `pinentry-gnome3` is installed and setup (`sudo update-alternatives --config pinentry`) it is not showing up. Neither for SSH (`trezor-agent -c user@host`) nor GPG (`GNUPGHOME=~/.gnupg/trezor gpa`). For SSH it is just annoying, because it uses the text version in the console. But for GPA it is unfortunately unusable, as there is no way at all to enter the pin.

I even tried adding the line `pinentry-program /usr/bin/pinentry-gnome3` to `~/.gnupg/trezor/gpg-agent.conf` but this doesn't fix it either.

Is there any way to debug this? I tried `trezor-gpg unlock -vv` but there's no output regarding which pinentry is used. I even launched `pinentry-gnome3 -d` in a parallel terminal, but there's nothing happening... looks like trezor-agent doesn't even try to use it.

**Comment by romanz** [comment]
Thanks for reporting this issue!

**Comment by romanz** [comment]
The code is not using GnuPG's pinentry program for TREZOR's PIN entry - but a [Pythonic message box package](https://pypi.python.org/pypi/PyMsgBox) for getting the scrambled PIN from the user (see [here](https://github.com/romanz/trezor-agent/blob/bf294beb56ad293c15e9d71eefe2a8d047f6aa03/libagent/device/trezor.py#L16)).

**Comment by pruflyos** [comment]
OK... then the documentation here (at the end of the page) is outdated: https://github.com/romanz/trezor-agent/blob/master/doc/README-GPG.md

**Comment by pruflyos** [comment]
```
$ pip install pymsgbox
Requirement already satisfied: pymsgbox in ./.local/lib/python2.7/site-packages
```
Should pymsgbox launch a GUI?

**Comment by pruflyos** [comment]
I found the reason. On Ubuntu you have to install `sudo apt-get install python-tk` first. Now a GUI box is launched when I use `GNUPGHOME=~/.gnupg/trezor gpa`.

**Comment by romanz** [comment]
Thanks for the debugging!
Will update the documentation.
