### ISSUE TITLE
Ideas to make the documentation AWESOME!!!!

### ISSUE THREAD

**Issue by rendaw** [romanz/trezor-agent#203]
As a preface, I'd be glad to make these changes and open a PR if it would be helpful.

1. Add an overview - I wasn't sure what this project was and what it would allow me to do after reading the front page.
2. Collect installation notes into the INSTALL.md page - the GPG instructions duplicate the bit about installing trezor-agent and seem to use an old name `trezor_agent`.  GPG requirements aren't mentioned on the installation page.
3. Centralize GPG configuration notes - as someone who is new to the project I didn't know that "Identity creation" is required and is the primary setup process.  `export GNUPGHOME=~/.gnupg/trezor` is critical I think but it isn't mentioned until the section "Sample Usage (signature and decryption)" which I skipped based on the name, and it's repeated in a couple other random places without explanation.
4. Add a note to the SSH page declaring that no configuration is necessary.  I was expecting some configuration process and searched quite a bit with no success.
5. Overview the agent's modes of SSH operation.  My basic use case is scp and the first thing I looked for on the page was how I could use it, but that requires either using the shell (under "Advanced Usage" - I skipped that) or using `*-agent -- scp ...` which is a mode of operation that's used in an example but never explained.  My conclusion after reading the page was that you could only do `ssh` and had to sub in `*-agent` for the `ssh` command - scp, rsync, etc weren't supported.
6. Make the list of supported devices obvious on the front page
7. Make a prominent link to the DESIGN doc on the front page - I was actually looking for this when I first found the project.  Related to 1 (after figuring out what the project was about I wanted to confirm the design was sane).

Generally speaking making the organization of the document more apparent and introducing parallels (like, make both the GPG and SSH pages have the same structure) would also make the information easier to digest.  Using numbers also helps - they show when the sections are ending/continuing, better than headers for instance since it can be hard to judge font sizes and weights visually especially if there's a few paragraphs inbetween.

Some other random details:

* I think imperative mood would be good to describe tasks and instructions.  For example, in the GPG page "Git commit & tag signatures" could be about tags and signatures in the `trezor-agent` repository - renaming it "Sign Git commits and tags" is unambiguous and conventional.  I think most How-to headers would be clearer written this way.
* Can you only create one identity (per device)?  I believe that's the case, but it's not obvious to beginners.
* How does this work with multiple devices?  Multiple devices from different makers?  I'm guessing you'd need a new store directory for each device.  This could also be a feature request, if confirmed.
* I think videos should be deprioritized or mixed with the other content since they're harder to consume.  You can't copy/paste, sound can be problematic in many environments, it's hard to tell how big they are, they take you away from the content by opening a new page, etc.  One might be cool to have on the front page, and they look nice which might attract new users.
* I expected the links to TREZOR, KeepKey, etc to go to the documentation for those specific devices rather than the manufacturer pages because of where they were
* The fact that there are _two_ binaries you interact with for GPG and SSH would also be good somewhere.  `*-agent` isn't obviously for SSH so if users get confused they may try that app for GPG without realizing that's a separate binary.

**Comment by romanz** [comment]
Wow, thanks a lot for the great suggestions!
I would be very happy to improve the documentation - all the fixes you offered are more than welcome :)
I really appreciate the effort you put into this...

**Comment by romanz** [comment]
> imperative mood would be good to describe tasks and instructions

I agree.

> Can you only create one identity (per device)?

Since we use [SLIP-0013](https://github.com/satoshilabs/slips/blob/master/slip-0013.md) key derivation, each device can be used for multiple identities (e.g. different keys for different SSH servers).

> I'm guessing you'd need a new store directory for each device.

You're definitely right - the existing code needs to be changed.

> I think videos should be deprioritized

I agree - they could be moved to a separate section.

> links to TREZOR, KeepKey, etc

I'd be happy to fix those - please let me know if there are better URLs to use :)

> there are two binaries you interact with for GPG and SSH

This happened since I've implemented SSH-agent functionality first, and after a while @tphyahoo suggested to add GPG-agent functionality as well (#3). 
The naming is indeed unfortunate... I would like to hear you opinion on improving it :)

**Comment by rendaw** [comment]
Thanks for reading this and I should apologize for making such extensive suggestions totally out of nowhere.  Thanks to this project I'm finally where I want to be with regards to computer security which was a personal goal.

Just to clarify, would it be okay for me to open a PR with doc changes?  Or did you want to make the changes yourself?

> each device can be used for multiple identities

Got that now, thanks to your other reply and some playing around :)

>> new store directory for each device

> the existing code needs to be changed

Just for the record, I only have one Trezor so I don't need this feature, but it might be cool to have.  I think just mentioning this current restriction in the docs might be good though, in case someone with multiple devices gets some unexpected behavior.

> please let me know if there are better URLs

Maybe you could use https://github.com/romanz/trezor-agent/blob/master/doc/INSTALL.md#trezor https://github.com/romanz/trezor-agent/blob/master/doc/INSTALL.md#keepkey and https://github.com/romanz/trezor-agent/blob/master/doc/INSTALL.md#ledger-nano-s ?  But that would be confusing as well if people skipped to those instructions without reading the rest.

Actually, I think it might be better here to move the list of supported devices to the overview and then have just the link to the installation instructions in the Installation section.

> I would like to hear you opinion on improving it

I'm probably not the right person to ask for that, I name my projects things like `trezor-gpg-pinentry-tk` haha.  To be honest though I don't think it's that bad as long as it's explained up front in the documentation.

**Comment by romanz** [comment]
Sounds great - please open a PR for improving the documentation, and I'll be happy to merge it :)

**Comment by rendaw** [comment]
PR merged
