### ISSUE TITLE
SSH identity positional parameter

### ISSUE THREAD

**Issue by rendaw** [romanz/trezor-agent#204]
I was trying to figure out what I need to specify for the identity parameter when running a command, like `trezor-agent some@identity -- ssh me@server`, but AFACIT from the source code it isn't used.

My understanding of the parameter is this:

1. When printing public keys, this is added as the identifier to the key (for identifying the owner of a key in authorized_hosts)
2. When connecting with `-c`, this is the user and server to connect to

Would it make sense to split these (print public key, connect, run command) into separate subcommands with distinct arguments?  I thought the name `identity` was a bit confusing in the context of `-c` as well.

**Comment by romanz** [comment]
The identity parameter is used to derive the public keys (from the hardware device, using [SLIP-0013](https://github.com/satoshilabs/slips/blob/master/slip-0013.md)), and to choose the private key to perform the digital signature (when authenticating to the remote SSH server).

> name identity was a bit confusing in the context of -c

I agree - and splitting the functionality into separate sub-commands would be indeed better.

**Comment by rendaw** [comment]
Ah, I see.  I think I get it now.

1. Exporting a public key - the identity is used to derive the key and adds it as a "comment" to the key definition
2. Connecting - the identity is the user@host to connect to.  The identity is also added to the identity list the agent sends to ssh when it asks for identities, and then used to derive the key to connect to.  Does this mean that to connect to a@b.com you need to export a public key for a@b.com to put in authorized_hosts when using -c?
3. Daemon/shell - Like in 2 the identity is added to the identity to send to ssh, and then to connect.

I'm not sure if you want to close this ticket or use it for something, but it might be something good to add to the docs if you weren't planning on separating subcommands in the near future.

And thanks for bearing with my muddled questions :) !

**Comment by romanz** [comment]
No problem :)

> Does this mean that to connect to a@b.com you need to export a public key for a@b.com to put in authorized_hosts when using -c?

Yes - and this is probably needs better documentation, as you suggested...
I'll open an issue to re-design the subcommand CLI for the SSH tool.

**Comment by romanz** [comment]
Sub-commands redesign will be tracked by #208
