### ISSUE TITLE
trezor-gpg init fails with "string overflow" exception when long passphrases are used

### ISSUE THREAD

**Issue by TreyFiello** [romanz/trezor-agent#207]
Steps to reproduce:

1. Enable passphrase use using the Trezor web wallet

2. `$ trezor-gpg init test@test.com` and when prompted for a passphrase enter: `abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ`

3. Note the `trezorlib.client.CallException: (3, u'string overflow')` thrown

**Comment by romanz** [comment]
IIUC, there is a limit on the passphrase size here:
https://github.com/trezor/trezor-mcu/blob/7fa8ae136fc45ddfae94ff54be8fd763dc6b159a/firmware/protob/messages.options#L29

Note that `len('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ') = 52` :)

**Comment by TreyFiello** [comment]
@romanz thanks -- looks like the change will have to come from Trezor's end if it's even possible. Closing.
