### ISSUE TITLE
[ledger] Can't force-push using trezor-git

### ISSUE THREAD

**Issue by instagibbs** [romanz/trezor-agent#21]
$ ~/Documents/project$ trezor-git push origin branchname -f
usage: trezor-git [-h] [-v] [-e CURVE] [--timeout TIMEOUT] [--debug]
                  [-r REMOTE] [-t]
                  [ARGUMENT [ARGUMENT ...]]
trezor-git: error: unrecognized arguments: -f

If you need any more help duplicating this let me know.

**Comment by romanz** [comment]
Please try running: `trezor-git -- push origin branchname -f`
It seems that Python's `argparse` module gets confused when it gets a '-f' (as a part of the Git command) and try to associate it with `trezor-git` arguments.

**Comment by instagibbs** [comment]
Ok works thanks.
