### ISSUE TITLE
Permission denied (publickey)

### ISSUE THREAD

**Issue by L-Cafe** [romanz/trezor-agent#210]
This one is a bit tricky, so I will describe it as detailed as I possibly can.

Considerations:

- The names of my machines have been changed for obvious security reasons. I have two machines, the machine which shows this behaviour is nicknamed "notworking.machine.faketld" and the one which doesn't show this behaviour (meaning: you can log in successfully with a TREZOR token) will be referred to as "working.machine.faketlkd".
- notworking.machine.faketld is listening for SSH on port 666.
- working.machine.faketld is listening for SSH on port 1668.
- I'm using Krypton https://krypt.co.
- Unless otherwise specified, working.machine.faketld shows expected behaviour in all scenarios, and notworking.machine.faketld shows "Permission denied (publickey)." where it should authenticate correctly.
- I have tried different things, among which:
    - Made the server listen in a standard 22 SSH port.
    - Tried different TREZOR passwords, including no password at all.
    - Tried connecting to the machines explicitly specifying the port number (which generates a different pubkey than without a port specified, so I have to add it to the machine).
    - Unpaired Krypton.
    - Uninstalled Krypton.
    - Shifting CLI arguments order around.
    - Restarting the SSH daemon.
    - Restarting the whole machine.

Steps to follow (will only reproduce the path showing unexpected behaviour):

1. Generate a pubkey running `trezor-agent -v -e ed25519 user@notworking.machine.faketld`.
2. Also run `trezor-agent -v -e ed25519 user@notworking.machine.faketld:666` to generate the pubkey with the port.
3. Connect to the machine successfully (using Krypton), edit the authorized_keys file, adding the two generated keys, save, and quit.
4. Try to connect using either `trezor-agent -v -e ed25519 user@notworking.machine.faketld -c` or `trezor-agent -v -e ed25519 user@notworking.machine.faketld:666 -c`.
5. Both attempts will fail giving a pubkey error.

Repeating the same steps for working.machine.faketld results in a connection success.

Is there something I'm missing? Can I have trezor-agent show me the actual pubkey it's using on a connection by using a certain argument?

**Comment by romanz** [comment]
Please try the following:
```
$ trezor-agent -vv -e ed25519 user@notworking.machine.faketld > trezor.pub
$ [add trezor.pub to ~/.ssh/authorized_keys on the target machine]
$ trezor-agent -vv -e ed25519 user@notworking.machine.faketld --shell
$ ssh -v user@notworking.machine.faketld -p 666
```
It would be great if you could send me the (verbose) output of the commands above (please use my PGP public key from https://keybase.io/romanz for encryption).

**Comment by L-Cafe** [comment]
All machines are working now, even when using the commands which I stated not to work.

There does seem to be a strange undocumented limit regarding TREZOR passwords, though...

Currently, I'm using a 10 character, randomly generated password. If I tried longer passwords like 20 or 30 characters, the process would freeze forever after pressing the enter key. This issue is not present in the TREZOR cryptocurrency web wallet. Could this issue be related to what I'm experiencing? I did use a different password than the one I was using where I was having problems.

Here is the recording that shows this behaviour: https://asciinema.org/a/jp5r0kelGS6zDhCX1lurG6yHN

(I do press Ctrl+C near the end)

**Comment by romanz** [comment]
This is indeed weird...
I've tried to reproduce this issue using the following [patch](https://gist.github.com/romanz/8b56a31a0e3e542971e46de43e7c892f), but it seems to work on my machine.

Could you please re-run the command, but with higher verbosity?
```
$ trezor-agent -vv -e ed25519 longpassword.com
```

**Comment by romanz** [comment]
BTW, could you reproduce this issue using `trezorctl` tool?
```
$ trezorctl ping msg --passphrase-protection
```

**Comment by L-Cafe** [comment]
Yeah. Something is wrong with the trezor drivers.

Running the command with high verbosity changes nothing, as nothing is printed to the screen when stuck. I can send the recording regardless if you need it.

As for `trezorctl`, I used the following password: `<!BhzvF=mh&-?^\<srn<P3^5Ux6!W6_FCU9b6Vktp5@](;T]TbMm{yXt-2(qE'/8"gRD$rmn<E[g[-Rfhw9k\B^Kvs$P,!J)rk#9}vN)ChpE-#c(Kr[&">~:eUxk&A` (So you can test it out too, but any long enough password should work, really). I also tested `3329223972424292228934589764775535858548856452766474982557765436349276654329376545555675542855965323587689572867799585834647587` afterwards, without recording the process, and it gets stuck in exactly the same way as the recording shows.

Here's the recording: https://asciinema.org/a/2sTjaeqnaIY2PZ1feSNHXt3Ux (Again, I press Ctrl+C after a while).

**Comment by L-Cafe** [comment]
I kept testing, and I stumbled across what could be the culprit. The TREZOR client claims "String overflow" and somewhere in the code this is not adequately handled.

This password should work fine: `vheedkbtzxhzpzdeuhtunxtpwfdzknjavctswefhprkrsrrbeu` (50 lowercase letters).
This password triggers the error: `phpnrspmgfmccmqbqhzwctckjyazqthpybmtypwnxwveqrxbjtt` (51 lowercase letters).
This password causes the "stuck" behaviour: `zfrvhxzspzyjumynugjbwmjjbuhrcdypvgdfwcudgtspnahksbjhdk` (54 lowercase letters).

So, to cut a long story short: Any password shorter than 51 characters, works. Any password between 51 and 53, both inclusive, spit an error. Any password longer than 53 characters gets stuck indefinitely.

This is the error message for the passwords that spit an error:
```
$ trezorctl ping msg --passphrase-protection
Passphrase required:

Confirm your Passphrase:

Traceback (most recent call last):
  File "/usr/local/bin/trezorctl", line 847, in <module>
    cli()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/bin/trezorctl", line 129, in ping
    return connect().ping(message, button_protection=button_protection, pin_protection=pin_protection, passphrase_protection=passphrase_protection)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 123, in wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 137, in wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 596, in ping
    return self.call(msg)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 151, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 199, in call
    resp = self.call(msg)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 151, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 196, in call
    msg = handler(resp)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 208, in callback_Failure
    raise CallException(msg.code, msg.message)
trezorlib.client.CallException: (3, 'string overflow')
```

Hopefully that makes more sense to you than it does to me, because all I can think of is either the TREZOR driver or the device itself acting funny.

**Comment by romanz** [comment]
https://github.com/romanz/trezor-agent/issues/207

**Comment by romanz** [comment]
Many thanks for debugging this!
Can confirm that the issue reproduces on my machine: 
[![asciicast](https://asciinema.org/a/1QMiha7296WucVpTsuKD49ct2.png)](https://asciinema.org/a/1QMiha7296WucVpTsuKD49ct2)

**Comment by romanz** [comment]
IIUC, this probably happens due to "tiny mode" [limitation](https://github.com/trezor/trezor-mcu/blob/d5e49556c5f96e10f56e000849a2c5669d576b9f/firmware/messages.c#L328)... (CC @prusnak).
I guess that we should limit the passphrase length at client-side (https://github.com/romanz/trezor-agent/commit/54ce6f2cec94fe07635b0c18e04819bff6d9e3ac).

**Comment by prusnak** [comment]
I confirm that passphrase is limited to 50 characters currently and the
limit should be applied in the client side.
I plan to remove this limitation on TREZOR One eventually, but no ETA.
TREZOR model T does not have this limitation.

**Comment by romanz** [comment]
Thanks, Pavol!
