### ISSUE TITLE
Cancelling PIN entry

### ISSUE THREAD

**Issue by rendaw** [romanz/trezor-agent#218]
Right now if you cancel PIN entry it's retried 4 times - you end up canceling 5 times to abort the operation.  I believe this happened with the old PIN entry code too (ex: closing the window).

I think the PIN entry should only be retried if the PIN is wrong (or maybe if there's a connection issue, although I'm not sure USB connection issues typically resolve when retried), otherwise an error should be logged and it should quit.

This isn't particularly important, but it would be nice to have.

**Comment by romanz** [comment]
Good point, thanks for catching this!
