### ISSUE TITLE
Handler.options should only be cleared when the connection ends

### ISSUE THREAD

**Issue by rendaw** [romanz/trezor-agent#219]
I think.

The first time I invoke gpg, the agent gets OPTIONs, the commands to sign/encrypt/get key/whatever, then RESET is passed time.

The 2nd time and after I invoke gpg, the gpg agent is sent RESET after the HAVEKEY's finish, and before PKSIGN, so the pinentry doesn't get any options.

It looks like in the GPG code all options are kept until the client connection is closed via `session_env_*` commands: 
`session_env_new` is called here: https://github.com/gpg/gnupg/blob/f574aabeeb873f14a586f80cac16b857e6088534/agent/gpg-agent.c#L3079
Then a thread to handle the connection is started which eventually gets to this:
https://github.com/gpg/gnupg/blob/f574aabeeb873f14a586f80cac16b857e6088534/agent/gpg-agent.c#L2708 - `start_command_handler` runs until EOF handling assuan commands, then `agent_deinit_default_ctrl` calls `session_env_release`.

At least, I think that's the issue.  Right now my pinentry is failing to appear unless I restart trezor-gpg-agent in any case.

**Comment by romanz** [comment]
Thanks for reporting this issue!

Could you please attach the logs (from `~/.gnupg/trezor/gpg-agent.log`)?
I am not sure I understand the scenario, since on my machine (Ubuntu 17.10, `gpg 2.1.15`) the code seems to work as intended.

**Comment by rendaw** [comment]
Yeah sure: https://gist.github.com/rendaw/0a079ba4511aeb8ec5aa3c5f9a979dd1

To demonstrate the issue I did:
```
gpg --sign ~/a.txt
(unplug trezor and plug in again to cause cash to clear)
gpg --sign ~/a.txt
```

The second time the pinentry didn't appear.  Waiting 5 minutes or whatever before signing works too.  Basically only the first gpg use with pinentry after starting the agent works.

If your trezor-gpg-agent started with `DISPLAY` in the environment it might be falling back to that.

**Comment by romanz** [comment]
Great catch - thanks a lot for the debugging!

**Comment by romanz** [comment]
Please take a look :)

**Comment by rendaw** [comment]
Whoops, sorry for the delay.  The fix is working great for me!

**Comment by romanz** [comment]
You're welcome :)
