### ISSUE TITLE
[ledger] GPG Issues

### ISSUE THREAD

**Issue by instagibbs** [romanz/trezor-agent#22]
GPG version is 2.1.12

I created a key successfully, but when I try to use my secret key, it complains and the agent dies, with nothing showing up on my Ledger Nano S screen. Let me know what else you may need to diagnose this.

>$ echo "Hello World!" | gpg2 --sign | gpg2 --verify
gpg: using "EA6311CA" as default secret key for signing (this appears to be the correct key)
gpg: signing failed: End of file
Traceback (most recent call last):
  File "/usr/local/bin/trezor-gpg", line 9, in <module>
gpg: signing failed: End of file
    load_entry_point('trezor-agent==0.6.5', 'console_scripts', 'trezor-gpg')()
  File "build/bdist.linux-x86_64/egg/trezor_agent/gpg/__main__.py", line 90, in main
  File "build/bdist.linux-x86_64/egg/trezor_agent/gpg/__main__.py", line 66, in run_agent
  File "build/bdist.linux-x86_64/egg/trezor_agent/gpg/agent.py", line 125, in handle_connection
  File "build/bdist.linux-x86_64/egg/trezor_agent/gpg/agent.py", line 42, in pksign
AssertionError
gpg: no signature found
gpg: uncompressing failed: No data
gpg: the signature could not be verified.
Please remember that the signature file (.sig or .asc)
should be the first file given on the command line.
$ 
[1]+  Exit 1                  trezor-gpg agent

**Comment by btchip** [comment]
Random questions, did you set your TREZOR_GPG_USER_ID to a new identity or an already existing identity in your keyring ? Is it a primary key ?

**Comment by romanz** [comment]
It seems to fail due to incorrect hashing algorithm required for GPG signature:
https://github.com/romanz/trezor-agent/blob/master/trezor_agent/gpg/agent.py#L42

Could you verify that you are using the correct ECDSA GPG key for signatures (i.e. is `EA6311CA` the newly created key)?

**Comment by romanz** [comment]
Please try this commit to see the actual hash ID:
https://github.com/romanz/trezor-agent/commit/030ae4c3f625ff2822686f16f6100ded555eb2cf

**Comment by instagibbs** [comment]
@btchip 
>Random questions, did you set your TREZOR_GPG_USER_ID to a new identity or an already existing identity in your keyring ? Is it a primary key ? 

My user ID is unique, I appended "Ledger" to make sure I could find the new key.

@romanz 
>Could you verify that you are using the correct ECDSA GPG key for signatures (i.e. is EA6311CA the newly created key)?  

That is the newly created/imported one yes.

>Please try this commit to see the actual hash ID: 030ae4c

AssertionError: Unsupported hash algorithm ID 10

**Comment by romanz** [comment]
Hash algorithm ID 10 is SHA512: https://tools.ietf.org/html/rfc4880#section-9.4
It's a bit weird, because the public key is created with SHA256 (algorithm ID 8) here: https://github.com/romanz/trezor-agent/blob/master/trezor_agent/gpg/encode.py#L98

**Comment by romanz** [comment]
Could you please post here the your public key's PGP packets?
```
$ gpg2 --export | gpg2 --list-packets
```

**Comment by instagibbs** [comment]
>:user ID packet: "Gregory Sanders Ledger <gsanders87@gmail.com>"
# off=440997 ctb=88 tag=2 hlen=2 plen=121
:signature packet: algo 19, keyid 8FAF3E989DB82B1A
        version 4, created 1471014120, md5len 0, sigclass 0x13
        digest algo 8, begin of digest 77 2e
        hashed subpkt 2 len 4 (sig created 2016-08-12)
        hashed subpkt 11 len 1 (pref-sym-algos: 9)
        hashed subpkt 27 len 1 (key flags: 03)
        hashed subpkt 21 len 1 (pref-hash-algos: 8)
        hashed subpkt 22 len 1 (pref-zip-algos: 0)
        hashed subpkt 23 len 1 (key server preferences: 80)
        subpkt 16 len 8 (issuer key ID 8FAF3E989DB82B1A)
        subpkt 100 len 10 (experimental / private subpacket)
        data: [254 bits]
        data: [255 bits]

**Comment by instagibbs** [comment]
Ok thanks to @btchip got this fixed. I had SHA512 as the first `personal-digest-preference`. I changed this to SHA256 and good to go. I had changed it because GPG had decided SHA1 was the best default :)

**Comment by instagibbs** [comment]
Ok, we might want to note that the key for signing is chosen via the environment variable that is set, and if you have 2 keys with the same uid, it just picks one(first in list-keys?)

**Comment by romanz** [comment]
@instagibbs good point - currently `trezor-agent`'s code doesn't support this case.
I will take a look and try to make it work...

**Comment by fansari** [comment]
I have a similar issue but perhaps just some stupid mistake.

The setup of the gpg key works. But then the first test fails:
```
[fansari@bat ~]$ echo "Hello World!" | gpg2 --sign
gpg: no default secret key: No secret key
gpg: signing failed: No secret key
```

**Comment by romanz** [comment]
Could you please run the following command to see if there are multiple keys with the same user ID:

```
$ gpg -k $TREZOR_GPG_USER_ID
```

**Comment by fansari** [comment]
[fansari@bat ~]$ gpg2 -k $TREZOR_GPG_USER_ID
pub   nistp256 2016-09-03 [SC]
      4D458E043BFA312ABCF24DA8754A6607A3732797
uid           [ultimate] Frank Ansari <mail@frank-ansari.de>
sub   nistp256 2016-09-03 [E]

**Comment by romanz** [comment]
Well, it seems indeed as a different issue :(
I have opened #29 - let's continue the discussion there.
