### ISSUE TITLE
Documenting GPG key creation time for backup

### ISSUE THREAD

**Issue by btchip** [romanz/trezor-agent#23]
There's already an option to set it - but it's IMHO important to highlight in the documentation that users should write it down / assign a fixed value when creating the key as this part is not available on device, and would prevent from generating a key with the same ID when restoring.

It could also be part of a wider abstraction for devices offering a secure RTC.

**Comment by instagibbs** [comment]
AFAICT, there is no way, outside of setting `-t` during creation, to actually see what the exact timestamp is. I haven't been able to find such an option in gpg anyways. So outputting the timestamp at a minimum without the `-t` option would be very useful.

**Comment by romanz** [comment]
@btchip @instagibbs what do you think about https://github.com/romanz/trezor-agent/commit/27a3fddfa2c32922bd48a5e46bc95a90f24573e0?

**Comment by btchip** [comment]
looks good to me

**Comment by instagibbs** [comment]
LGTM
