### ISSUE TITLE
Test for Homebrew formula

### ISSUE THREAD

**Issue by menteb** [romanz/trezor-agent#231]
For the Homebrew Formula I need to do a test for it to pass and get merged.
Previously `trezor-agent identity@myhost` gave the message "Trezor not connected", but now I get the error below. Any idea on what went wrong? The Formula showing all the packages and their versions is here: https://github.com/Homebrew/homebrew-core/pull/22537/files

> trezor-agent identity@myhost
> 2018-04-05 11:50:27,204 WARNING      DISPLAY not defined                                                                                  [ui.py:65]
> Traceback (most recent call last):
>   File "/usr/local/bin/trezor-agent", line 11, in <module>
>     load_entry_point('trezor-agent==0.9.2', 'console_scripts', 'trezor-agent')()
>   File "/usr/local/Cellar/trezor-agent/0.9.2/libexec/bin/trezor_agent.py", line 5, in <lambda>
>     ssh_agent = lambda: libagent.ssh.main(DeviceType)
>   File "/usr/local/Cellar/trezor-agent/0.9.2/libexec/lib/python3.6/site-packages/libagent/ssh/__init__.py", line 164, in wrapper
>     return func(*args, **kwargs)
>   File "/usr/local/Cellar/trezor-agent/0.9.2/libexec/lib/python3.6/site-packages/libagent/ssh/__init__.py", line 287, in main
>     for pk in conn.public_keys():
>   File "/usr/local/Cellar/trezor-agent/0.9.2/libexec/lib/python3.6/site-packages/libagent/ssh/__init__.py", line 199, in public_keys
>     self.public_keys_cache = conn.export_public_keys(self.identities)
>   File "/usr/local/Cellar/trezor-agent/0.9.2/libexec/lib/python3.6/site-packages/libagent/ssh/client.py", line 24, in export_public_keys
>     with self.device:
>   File "/usr/local/Cellar/trezor-agent/0.9.2/libexec/lib/python3.6/site-packages/libagent/device/interface.py", line 118, in __enter__
>     self.conn = self.connect()
>   File "/usr/local/Cellar/trezor-agent/0.9.2/libexec/lib/python3.6/site-packages/libagent/device/trezor.py", line 98, in connect
>     transports = self._defs.enumerate_transports()
>   File "/usr/local/Cellar/trezor-agent/0.9.2/libexec/lib/python3.6/site-packages/libagent/device/trezor.py", line 24, in _defs
>     from . import trezor_defs
>   File "/usr/local/Cellar/trezor-agent/0.9.2/libexec/lib/python3.6/site-packages/libagent/device/trezor_defs.py", line 8, in <module>
>     from trezorlib.device import TrezorDevice
>   File "/usr/local/Cellar/trezor-agent/0.9.2/libexec/lib/python3.6/site-packages/trezorlib/device.py", line 23, in <module>
>     from .transport_webusb import WebUsbTransport
>   File "/usr/local/Cellar/trezor-agent/0.9.2/libexec/lib/python3.6/site-packages/trezorlib/transport_webusb.py", line 24, in <module>
>     import usb1
>   File "/usr/local/Cellar/trezor-agent/0.9.2/libexec/lib/python3.6/site-packages/usb1/__init__.py", line 61, in <module>
>     from . import libusb1
>   File "/usr/local/Cellar/trezor-agent/0.9.2/libexec/lib/python3.6/site-packages/usb1/libusb1.py", line 199, in <module>
>     libusb = _loadLibrary()
>   File "/usr/local/Cellar/trezor-agent/0.9.2/libexec/lib/python3.6/site-packages/usb1/libusb1.py", line 173, in _loadLibrary
>     return dll_loader('libusb-1.0' + suffix, **loader_kw)
>   File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ctypes/__init__.py", line 348, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: dlopen(libusb-1.0.dylib, 6): image not found

**Comment by romanz** [comment]
It seems that the latest version of `python-trezor` is using `usb1` Python pacakge, which tries to load `libusb-1.0` shared library (which should be installed as described [here](https://github.com/trezor/python-trezor#install)).

**Comment by menteb** [comment]
Roger, missed that one. Formula fixed and waiting for merge.
Now up to date with trezor-agent 0.9.2 & libagent 0.11.2.
