### ISSUE TITLE
Add lifetime/timeout option for SSH and GPG agents

### ISSUE THREAD

**Issue by aceat64** [romanz/trezor-agent#236]
It would be great to have an option to clear the password from the agent after a set timeout (configurable via command line) so that the user has to input their password again.

For instance, I use my Trezor at work but I keep my desktop running 24/7. This means that if I put in the password for my SSH key or GPG identity, I have to kill the trezor-agent and trezor-gpg-agent processes manually if I want to remove that password from memory.

**Comment by romanz** [comment]
Thanks for the suggestion :)
Will add this feature soon.

**Comment by romanz** [comment]
> It would be great to have an option to clear the password from the agent after a set timeout (configurable via command line) so that the user has to input their password again.

@aceat64 Just to make sure - did you mean [passphrase](https://blog.trezor.io/hide-your-trezor-wallets-with-multiple-passphrases-f2e0834026eb) above (instead of *password*)?

**Comment by aceat64** [comment]
That's correct, I meant passphrase. I tend to use password/passphrase interchangeably.

**Comment by romanz** [comment]
Let me know if you'd like to set this via a command-line flag, or change the default value (at https://github.com/romanz/trezor-agent/commit/6e114282461a0f3618e3fc84cc10ca54a5fe6dfb).

**Comment by aceat64** [comment]
I think a command line flag would be best. I imagine there are arguments to be made for both longer and shorter time frames. Will it also be possible to set it to never expire (current behavior)?

**Comment by romanz** [comment]
Sounds good, will update the code tomorrow.
