### ISSUE TITLE
GPG symmetric encryption not supported

### ISSUE THREAD

**Issue by Epse** [romanz/trezor-agent#239]
When using GPG to symmetrically encrypt a file using `gpg -o file.gpg -c file` it errors out with:

    gpg: problem with the agent: Not supported
    gpg: error creating passphrase: Operation cancelled
    gpg: symmetric encryption of 'filename' failed: Operation cancelled

Signing and asymmetric encryption works

**Comment by romanz** [comment]
Thanks for reporting this issue!
Will add support for this feature soon.

**Comment by Epse** [comment]
Thanks!
