### ISSUE TITLE
trezorlib marking hidapi dep as optional

### ISSUE THREAD

**Issue by matejcik** [romanz/trezor-agent#241]
just a heads-up: we're marking the hidapi dependency (required for T1) as optional: trezor/python-trezor@41d9976

you might want to update that in the relevant `setup.py`:
```
trezor[hidapi]>=0.9.0
```
i'll send a PR later if you want

**Comment by romanz** [comment]
Thanks for update!

**Comment by romanz** [comment]
Released at https://pypi.org/project/libagent/0.11.3/
