### ISSUE TITLE
feature: support for IdentitiesOnly

### ISSUE THREAD

**Issue by matejcik** [romanz/trezor-agent#247]
I spent an afternoon figuring out how this works, so here are the results of my research :)

-----

**One,** to make trezor-agent work with `IdentitiesOnly`, follow these steps:

1. save your public key to a file. Let's say:
   ```sh
   trezor-agent user@example.com > ~/.ssh/example-identity.pub
   ```
2. edit your `~/.ssh/config` and add the following:
   ```
   Host example.com
     User user
     IdentityFile ~/.ssh/example-identity.pub
   ```
   Then login without other arguments with `ssh example.com`, or `trezor-agent -c user@example.com`, whichever is appropriate in the environment...
   This should work for all uses of ssh, so git/mercurial, sshfs, etc.
3. Alternately, supply the identity file on command line
   ```sh
   ssh -i ~/.ssh/example-identity.pub example.com -l user
   ```

-----

**Two,** `trezor-agent -c` should do this implicitly, so that support for `IdentitiesOnly` is transparent.
Just dump the public key line into a temporary file and execute ssh `-i /tmp/aslfjsadghen`

Three, perhaps dumping to `~/.ssh` could also be a semi-default behavior, possibly enabled by a switch?  If you came up with a good naming scheme for the files. That way you'd get a persistent list of your identities, if you wanted it, and a more discoverable path to the config suggested above.

**Comment by romanz** [comment]
Fixed by https://github.com/romanz/trezor-agent/commit/672af98ad7814c3841b80d920665baa652f9b81d and https://github.com/romanz/trezor-agent/commit/8672a6901a636bd0232a5eb6bd2d06051a44914a.

**Comment by romanz** [comment]
> Three, perhaps dumping to ~/.ssh could also be a semi-default behavior, possibly enabled by a switch? If you came up with a good naming scheme for the files. That way you'd get a persistent list of your identities, if you wanted it, and a more discoverable path to the config suggested above.

This can be a really nice feature, will open a separate issue.

**Comment by TCM2** [comment]
How is `-i <pubkey>` supposed to work at all? The argument to `-i` is a private key, so when I try to supply a public key, all I get is a prompt `Enter passphrase for key '[...].pub':` as expected.

What am I missing?
