### ISSUE TITLE
GPG pip install fail

### ISSUE THREAD

**Issue by rustyrussell** [romanz/trezor-agent#25]
```
$ pip install --user git+https://github.com/romanz/trezor-agent.git@gpg-agent
Collecting git+https://github.com/romanz/trezor-agent.git@gpg-agent
  Cloning https://github.com/romanz/trezor-agent.git (to gpg-agent) to /tmp/pip-MLFnJN-build
  Could not find a tag or branch 'gpg-agent', assuming commit.
error: pathspec 'gpg-agent' did not match any file(s) known to git.
Command "git checkout -q gpg-agent" failed with error code 1 in /tmp/pip-MLFnJN-build

```

Indeed, there's no gpg-agent branch to be found on github?  Seems it's merged and instructions not updated?

**Comment by romanz** [comment]
Thanks for reporting this issue!
I indeed forgot to update the documentation...

**Comment by romanz** [comment]
Unfortunately, I am currently away from my computer... I will fix the documentation during the weekend, when I'll return home.

**Comment by romanz** [comment]
Fixed at https://github.com/romanz/trezor-agent/commit/d63f048b7845646c91741415469749725157fd82
