### ISSUE TITLE
Recovery failed. Error details: hidapi: failed to open device

### ISSUE THREAD

**Issue by jimmyblockchain** [romanz/trezor-agent#250]
I get this error when trying to upgrade the firmware.  Even after wiping the device.  Stuck on the PIN Screen of Trezor and cannot access MEW.

**Comment by romanz** [comment]
I'm not sure that this error is related to `trezor-agent`.
Could you please record your session with https://asciinema.org/?

**Comment by ravi4chahal** [comment]
trezor hidapi: failed to open device 

Getting this error in recent version of Mac Beta (10.15)

**Comment by romanz** [comment]
Does trezorctl work?
