### ISSUE TITLE
SSH Fails at "Please confirm user login"

### ISSUE THREAD

**Issue by MAHDTech** [romanz/trezor-agent#258]
Hi,

firstly, thanks for making this project, it's awesome!

I'm testing using the following setup and have come across an issue.

* Trezor One
* OpenSUSE Leap
* Running on Windows Subsystem for Linux

I can successfully use the agent to determine the public key, however when attempting to use git, or SSH to another host I am receiving the following error, am I missing an additional library due to WSL?

> debug1: Server accepts key: pkalg ssh-ed25519 blen 51
> 2018-08-18 19:17:35,500 INFO         please confirm user "git" login to "<ssh://git@gitlab.com|ed25519>" using Trezor...                  [client.py:46]
> sign_and_send_pubkey: signing failed: communication with agent failed
> debug1: No more authentication methods to try.
> 2018-08-18 19:17:35,507 WARNING      error: module 'ctypes' has no attribute 'windll'                                                     [server.py:100]
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/site-packages/libagent/server.py", line 95, in handle_connection
>     reply = handler.handle(msg=msg)
>   File "/usr/lib/python3.6/site-packages/libagent/ssh/protocol.py", line 103, in handle
>     reply = method(buf=buf)
>   File "/usr/lib/python3.6/site-packages/libagent/ssh/protocol.py", line 144, in sign_message
>     signature = self.conn.sign(blob=blob, identity=key['identity'])
>   File "/usr/lib/python3.6/site-packages/libagent/ssh/__init__.py", line 235, in sign
>     return conn.sign_ssh_challenge(blob=blob, identity=identity)
>   File "/usr/lib/python3.6/site-packages/libagent/ssh/client.py", line 48, in sign_ssh_challenge
>     with self.device:
>   File "/usr/lib/python3.6/site-packages/libagent/device/interface.py", line 118, in __enter__
>     self.conn = self.connect()
>   File "/usr/lib/python3.6/site-packages/libagent/device/trezor.py", line 109, in connect
>     transports = self._defs.enumerate_transports()
>   File "/usr/lib/python3.6/site-packages/libagent/device/trezor_defs.py", line 13, in enumerate_transports
>     return TrezorDevice.enumerate()
>   File "/usr/lib/python3.6/site-packages/trezorlib/device.py", line 32, in enumerate
>     return enumerate_devices()
>   File "/usr/lib/python3.6/site-packages/trezorlib/transport/__init__.py", line 90, in enumerate_devices
>     for transport in all_transports():
>   File "/usr/lib/python3.6/site-packages/trezorlib/transport/__init__.py", line 77, in all_transports
>     module = importlib.import_module("." + modname, __name__)
>   File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/usr/lib/python3.6/site-packages/trezorlib/transport/hid.py", line 18, in <module>
>     import hid
>   File "/usr/lib/python3.6/site-packages/hid/__init__.py", line 24, in <module>
>     hidapi = ctypes.windll.LoadLibrary('hidapi.dll')
> AttributeError: module 'ctypes' has no attribute 'windll'git@gitlab.com: Permission denied (publickey).

**Comment by MAHDTech** [comment]
This issue is fixed by installing the following additional packages using pip

* hid
* hidapi

`pip3 install hid hidapi`

**Comment by romanz** [comment]
> firstly, thanks for making this project, it's awesome!

Thanks, much appreciated!

> This issue is fixed by installing the following additional packages using pip

Good point - updated the installation doc: https://github.com/romanz/trezor-agent/commit/71f357c1bfc76bd8260e4cd7f079372c3063cfce
