### ISSUE TITLE
GPG Assertion Error

### ISSUE THREAD

**Issue by MAHDTech** [romanz/trezor-agent#262]
Hi,

when testing the trezor-gpg-agent I am receiving the following error, any tips to fix this?

```bash
2018-09-10 02:36:08,236 ERROR        handler failed:                                                                                      [__init__.py:273]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/libagent/gpg/__init__.py", line 265, in run_agent
    handler.handle(conn)
  File "/usr/lib/python3.6/site-packages/libagent/gpg/agent.py", line 242, in handle
    handler(conn, args)
  File "/usr/lib/python3.6/site-packages/libagent/gpg/agent.py", line 102, in <lambda>
    b'HAVEKEY': lambda _, args: self.have_key(*args),
  File "/usr/lib/python3.6/site-packages/libagent/gpg/agent.py", line 205, in have_key
    self.get_identity(keygrip=keygrip)
  File "/usr/lib/python3.6/site-packages/libagent/util.py", line 230, in wrapper
    result = method(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/libagent/gpg/agent.py", line 174, in get_identity
    assert pubkey.key_id() == pubkey_dict['key_id']
AssertionError
```

The steps to reproduce this were as follows:

* Attempted to list the Secret GPG Keys
```bash
gpg --list-secret-keys
```
* The Trezor then asks where to enter passphrase, I Pressed "Host"
* The Pinentry is then displayed on-screen where I entered no passphrase (don't have one configured yet)
* The error is then displayed in the gpg-agent.log

**Comment by MAHDTech** [comment]
Some additional info.

* Contents of the ~/.gnupg/trezor/gpg.conf

```bash
agent-program /home/user/.gnupg/trezor/run-agent.sh
personal-digest-preferences SHA512
```

* Contents of the /home/user/.gnupg/trezor/run-agent.sh

```bash
#!/bin/sh

export PATH=/home/user/bin:/home/user/bin:/usr/local/bin:/usr/bin:/bin:/home/user/bin:/bin:/home/user/go/bin:/home/user/bin:/bin:/home/user/go/bin:/home/user/bin:/bin:/home/user/go/bin

/usr/bin/trezor-gpg-agent \
-vv \
--pin-entry-binary=pinentry \
--passphrase-entry-binary=pinentry \
--cache-expiry-seconds=inf \
$*
```

**Comment by romanz** [comment]
Thanks for reporting this issue!

**Comment by romanz** [comment]
Does this work when choosing "Device" (when asked where to enter passphrase)?
Also, could you please attach the output of `gpg --list-keys`?

**Comment by sp4ke** [comment]
Just a heads up. I got the same error after I changed the primary uid on my key. I had to manually edit `gpg/agent.py` at change the default id index from `user_ids[0]` to the position of the new identity I made primary then I could edit the private key again and reset to the previous primary identity and restore the code changes. 

So question, is there a way to change the primary identity of a key with trezor-agent ?

**Comment by MAHDTech** [comment]
Thanks @sp4ke, that was the issue I had as well!

@romanz, is there a way to specify the uid via a config option?

**Comment by romanz** [comment]
Sorry for the delayed response...
Currently, we use [SLIP-0013](https://github.com/satoshilabs/slips/blob/master/slip-0013.md) and [SLIP-0017](https://github.com/satoshilabs/slips/blob/master/slip-0017.md) for generating signing and encryption keys on the device.
The identity (the UID in this case) to be "static" so the public key stay the same on future derivations... so currently we can't change the UID after public key is generated and shared with other users.
You can add more UIDs though using the `gpg --edit-key` [command](https://www.gnupg.org/gph/en/manual/r899.html).

**Comment by MAHDTech** [comment]
Thanks @romanz, that makes sense.

I had created a new UID, marked it as primary as I wanted to revoke the old UID no longer in use (invalid email).

Armed with this new knowledge of how it works I will use a single master UID that won't ever be revoked and simply add multiple additional UIDs as required.

Thank you!
