### ISSUE TITLE
Ledger-gpg init exits with “gpg: error reading key: No secret key” 

### ISSUE THREAD

**Issue by teardrop18** [romanz/trezor-agent#270]
I am using a Ledger Nano S with the Qubes operating system. I have it working perfectly with ledger-agent to manage my SSH keys.
I install all the necessary dependencies in a debian-9 based template and then I create a Qubes App VM that runs on top of this template. In this App VM I install the pip3 ledger-agent package and pass through my Ledger Nano S.

Subsequently, I have created a new Qubes App VM to use with ledger-gpg. After setting this up and passing through my Ledger Nano S I then run the instructed initialization command. After successfully using the Ledger to sign a PGP key it then concludes with a number of error messages:

```
~ >> ledger-gpg init "test <foo@bar.com>" -v
2018-10-23 18:55:19,374 WARNING      This GPG tool is still in EXPERIMENTAL mode, so please note that the API and features may change without backwards compatibility! [__init__.py:118]
gpg: WARNING: unsafe permissions on homedir '/home/user/.gnupg'
2018-10-23 18:55:19,385 INFO         device name: ledger                                                                                  [__init__.py:126]
2018-10-23 18:55:19,386 INFO         GPG home directory: /home/user/.gnupg/ledger                                                         [__init__.py:131]
2018-10-23 18:55:19,402 WARNING      NOTE: in order to re-generate the exact same GPG key later, run this command with "--time=1540317319" commandline flag (to set the timestamp of the GPG key manually). [__init__.py:35]
2018-10-23 18:55:25,668 INFO         creating new nist256p1 GPG primary key for "test <foo@bar.com>"                                      [__init__.py:63]
2018-10-23 18:55:25,669 INFO         please confirm GPG signature on LedgerNanoS for "<gpg://test <foo@bar.com>|nist256p1>"...            [client.py:35]
2018-10-23 18:55:28,000 INFO         please confirm GPG signature on LedgerNanoS for "<gpg://test <foo@bar.com>|nist256p1>"...            [client.py:35]
gpg: keybox '/home/user/.gnupg/ledger/pubring.kbx' created
gpg: armor header: Version: GnuPG v2
gpg: pub  nistp256/DAB0541DFFEC07AC 2018-10-23  test <foo@bar.com>
gpg: /home/user/.gnupg/ledger/trustdb.gpg: trustdb created
gpg: using pgp trust model
gpg: key DAB0541DFFEC07AC: public key "test <foo@bar.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: inserting ownertrust of 6
gpg: WARNING: unsafe permissions on homedir '/home/user/.gnupg'
gpg: Note: '--homedir' is not considered an option
gpg: keybox '/home/user/.gnupg/pubring.kbx' created
gpg: /home/user/.gnupg/trustdb.gpg: trustdb created
gpg: error reading key: No secret key
Traceback (most recent call last):
  File "/usr/local/bin/ledger-gpg", line 11, in <module>
    sys.exit(gpg_tool())
  File "/rw/usrlocal/bin/ledger_agent.py", line 6, in <lambda>
    gpg_tool = lambda: libagent.gpg.main(DeviceType)
  File "/usr/local/lib/python3.5/dist-packages/libagent/gpg/__init__.py", line 324, in main
    return args.func(device_type=device_type, args=args)
  File "/usr/local/lib/python3.5/dist-packages/libagent/gpg/__init__.py", line 199, in run_init
    '--homedir', homedir]))
  File "/usr/local/lib/python3.5/dist-packages/libagent/gpg/__init__.py", line 104, in check_call
    subprocess.check_call(args=args, stdin=stdin, env=env)
  File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/gpg', '--list-secret-keys', 'test <foo@bar.com>', '--homedir', '/home/user/.gnupg/ledger']' returned non-zero exit status 2
```

**Comment by romanz** [comment]
Could you please attach the log file (which should contain the actual traceback) from `~/.gnupg/ledger/gpg-agent.log`?

**Comment by teardrop18** [comment]
> Could you please attach the log file (which should contain the actual traceback) from `~/.gnupg/ledger/gpg-agent.log`?

Hi, 
Thank you for taking a look at this.
I navigated to that folder and could not find any log files.
Is there anything I need to set so that log file will be generated if I run the commands again?

**Comment by romanz** [comment]
Oops, my bad... you're right.
Could you please re-run the following command (with higher verbosity) and attach the debug log?
```
$ ledger-gpg init "test <foo@bar.com>" -vv
```

**Comment by romanz** [comment]
BTW, does the following command succeed?
```
$ gpg --list-secret-keys 'test <foo@bar.com>' --homedir '/home/user/.gnupg/ledger'
```

**Comment by romanz** [comment]
Could you please try the latest master (https://github.com/romanz/trezor-agent/commit/fec84288be7fbafa8a4f417d72cd87117f67ceee)?
I am asking since this issue seems a bit similar to https://github.com/romanz/trezor-agent/issues/268.

**Comment by teardrop18** [comment]
I've tried running it again and still get the same error but I'm not 100% sure I'm working with your latest code. 
What I did was: create a fresh new Qubes VM and clone the github repo https://github.com/romanz/trezor-agent/
then I ran ```pip3 install ./``` in the ```trezor-agent``` directory and also in the ```agents/ledger``` subdirectory. 
It still seems to be downloading a lot of stuff from "pythonhosted.org".

Please can you advise?

**Comment by romanz** [comment]
Could you try running the following command?
```
$ gpg --homedir /home/user/.gnupg/ledger --list-secret-keys 'test <foo@bar.com>'
```

**Comment by romanz** [comment]
In order to see which Python file is used, could you try running the following command (and attach the file according to its output)?
```
$ python3 -c "import libagent.gpg; print(libagent.gpg.__file__)"
```

**Comment by romanz** [comment]
I think that the file on your machine is not updated to the latest version (at GitHub):
https://github.com/romanz/trezor-agent/blob/fec84288be7fbafa8a4f417d72cd87117f67ceee/libagent/gpg/__init__.py#L197-L199

On your machine, it is:
```python
    # Load agent and make sure it responds with the new identity
    check_call(keyring.gpg_command(['--list-secret-keys', args.user_id,
                                    '--homedir', homedir]))
```

**Comment by romanz** [comment]
Consider uninstalling and the re-installing `libagent` from the latest version on GitHub.

**Comment by teardrop18** [comment]
I couldn't see an easy way to install libagent and ensure it was using the latest code on Github. Therefore I renamed the old __init__.py file and copied the latest one directly from Github in its place.
I am pleased to report that this resolved the issue and the init command subsequently worked as expected! :-)

Thank you for your help with this and all the hard work you have put into creating the ledger-agent program. As I mentioned before, I have been using it for SSH keys for a while and it works very well. I am looking forward to being able to use it with Enigmail to secure my emails.

I have some colleagues that will also be looking to use their Ledger Nanos to secure their emails so I wondered how soon will the latest code on Github be pushed out so it will be installed with the "pip3 install ledger-agent" command?

Also, last time I checked, your app for the Ledger Nano device was not available on the new Ledger Live program, do you know when it will be installable via this route?

**Comment by romanz** [comment]
> Thank you for your help with this and all the hard work you have put into creating the ledger-agent program.

My pleasure!

> I have some colleagues that will also be looking to use their Ledger Nanos to secure their emails so I wondered how soon will the latest code on Github be pushed out so it will be installed with the "pip3 install ledger-agent" command?

https://pypi.org/project/libagent/0.12.1/ :)

> Also, last time I checked, your app for the Ledger Nano device was not available on the new Ledger Live program, do you know when it will be installable via this route?

I am actually not sure, let's ask @btchip.
