### ISSUE TITLE
Support for additional curves

### ISSUE THREAD

**Issue by efab9c6f2b4c49578f8e619e27f6b3fb** [romanz/trezor-agent#271]
This is an incredibly valuable tool.

I manage some devices using SSH that rely upon different/older curve algorithms.  From reviewing the code my understanding is that both nist256p1 and ed25519 are supported.  Is there any plan to integrate other curves such as sha256?

**Comment by romanz** [comment]
`sha256` is a hashing algorithm, not an elliptic curve.

**Comment by efab9c6f2b4c49578f8e619e27f6b3fb** [comment]
Yes - pardon my ignorance for including incomplete/incorrect information :)

Primarily I would like to be able to use trezor-agent to store keys for OpenWRT, which uses Dropbear with curve25519-sha256@libssh.org by default (if my understanding is correct).  It's possible for me to enable ECC through compiling OpenWRT myself but would rather avoid this if possible.

Apologies in advance if I am not explaining this correctly.  The source for OpenWRT Dropbear config is here for reference - https://git.openwrt.org/?p=openwrt/openwrt.git;a=blob;f=package/network/services/dropbear/Config.in;h=ca0af9d5e078f3a4d0d9e02e034cd1e03ce40a2e;hb=refs/heads/master

**Comment by romanz** [comment]
No problem :)

trezor-agent should support ed25519 signatures, by passing `-e` command line flag.

**Comment by romanz** [comment]
For example, see:
https://github.com/romanz/trezor-agent/blob/master/doc/README-SSH.md#access-remote-gitmercurial-repositories
