### ISSUE TITLE
Homebrew support

### ISSUE THREAD

**Issue by menteb** [romanz/trezor-agent#273]
I will split up the install packages for Homebrew in the way that I want libagent to have its own Formula. Reason is that e.g. trezor-agent doesn't get a version bump when libagent get bumped up. 
Is there a small test I can use to see if the libagent library works without using trezor-agent or any of the other agents?

**Comment by romanz** [comment]
Many thanks for the help!

> Is there a small test I can use to see if the libagent library works without using trezor-agent or any of the other agents?

You can run `tox` (see [tox.ini](https://github.com/romanz/trezor-agent/blob/master/tox.ini) for details), or just run `py.test -v` in the root directory.

**Comment by jonathancross** [comment]
@menteb Any luck with the Homebrew package?

**Comment by menteb** [comment]
Haven't touched it in a while because of my PhD work... I need to have a look once I'm back from field research. Will need to split it from the library somehow, create tests for the library, and then make it a dependency for the main apps. Will try to push it into Homebrew before the end of May.

**Comment by jonathancross** [comment]
> Will try to push it into Homebrew before the end of May.

Thanks for you help @menteb -- were you able to make any progress on this?

**Comment by menteb** [comment]
Not yet. Been a bit sidetracked with my other stuff. Will try to have a look soon. Is the project still alive though? Last update was 6 months ago.

**Comment by jonathancross** [comment]
@romanz was working on https://github.com/romanz/trezor-agent/pull/293 last month, so it doesn't seem dead to me. :-)

**Comment by romanz** [comment]
The project is indeed not dead, I'm just a bit bust lately :)

**Comment by menteb** [comment]
Hahaha ok, so I'm not alone. Stay tuned I'd say. I'll have a look soon then

**Comment by menteb** [comment]
Ok, step one has been done. I requested a [merge](https://github.com/Homebrew/homebrew-core/pull/43601) for the libagent formula. Once that is done I'll create a new version for Trezor which reflects this dependency. I'll then also create two separate formula for Ledger and Keepas.

**Comment by menteb** [comment]
The sweet thing is that libagent will be able to function as a dependency for other formula.

**Comment by menteb** [comment]
Little update: Homebrew does not want python libraries added to the core. So `libagent` will remain a dependency. I am updating the `trezor-agent.rb` formally now so it installs Keepkey and Ledger agents together with Trezor. That way it's just one formula for everything as Homebrew requires a different GitHub repo per application.

**Comment by menteb** [comment]
I've updated to formula and requested a [merge](https://github.com/Homebrew/homebrew-core/pull/43931) with Homebrew core. Added the Ledger and Keepkey packages.

**Comment by menteb** [comment]
@romanz since there are 3 brands of hardware supported here, wouldn't it be clearer to rename the repository? Just a thought.

**Comment by menteb** [comment]
@jonathancross merge with Homebrew was successful. I'll update when either `libagent` or any of the apps get a version bump.

**Comment by romanz** [comment]
> @romanz since there are 3 brands of hardware supported here, wouldn't it be clearer to rename the repository?

TREZOR was the original HW wallet that supported this feature, therefore the naming.
In addition, I'd prefer to prevent existing URLs from breaking :)

**Comment by chenrui333** [comment]
👋  As we have this formula in homebrew-core, I think this issue can be closed. Thanks!
