### ISSUE TITLE
trezorlib 0.11 compatibility

### ISSUE THREAD

**Issue by matejcik** [romanz/trezor-agent#277]
There's been major API breakage in 0.11

I'm going to submit a PR, just filing this so that you know i'm working on it.

It might even be possible to stay compatible with 0.10

**Comment by romanz** [comment]
Thanks!
I was working on [latest-trezorlib](https://github.com/romanz/trezor-agent/commits/latest-trezorlib) branch (for supporting 0.11), but I'm not sure it is done correctly...

**Comment by matejcik** [comment]
I was thinking of reusing your UI class directly, actually. It has almost the same signature as what we require for `ui` parameter, and adding no-op (or maybe some-op) for `button_request` would not be a big deal. The only thing I'm wondering about is caching the passphrase.

**Comment by romanz** [comment]
> I was thinking of reusing your UI class directly, actually. It has almost the same signature as what we require for `ui` parameter, and adding no-op (or maybe some-op) for `button_request` would not be a big deal. 

Sounds great, thanks :)

> The only thing I'm wondering about is caching the passphrase.

This cache was added as a "hack", so feel free to ignore it - I can definitely re-add later.
