### ISSUE TITLE
Could not find a version that satisfies the requirement libagent>=0.13.0

### ISSUE THREAD

**Issue by LukasRada** [romanz/trezor-agent#279]
1. Install deps `apt-get install python3-pip python3-dev python3-tk libusb-1.0-0-dev libudev-dev`
2. Clone repo `git clone https://github.com/romanz/trezor-agent`
3. Run `pip3 install --user -e trezor-agent/agents/trezor`

Then error follows:
```
Could not find a version that satisfies the requirement libagent>=0.13.0 (from trezor-agent==0.10.0) (from versions: 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.9.8, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.12.0, 0.12.1)
No matching distribution found for libagent>=0.13.0 (from trezor-agent==0.10.0)
```
OS: Debian 9
pip3 -V
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.5)

What am I doing wrong?

**Comment by romanz** [comment]
Thanks for reporting this issue!
I forgot to update PyPI with the latest version of `libagent` - now it should be updated:
https://pypi.org/project/libagent/0.13.0/
https://pypi.org/project/trezor-agent/0.10.0/

Please try again :)

**Comment by LukasRada** [comment]
Great! It works :)
