### ISSUE TITLE
Trezor ECDSA 

### ISSUE THREAD

**Issue by nmfarshad** [romanz/trezor-agent#283]
Is there any way to sign a custom message using on of the private keys available on trezor ? 
ie. sign a msg using bip32 m/0/0 path private key ? output will be der encoded signature 

Could any one please advice or guide me in the correct direction to accomplish this ?

**Comment by romanz** [comment]
You should use sign_message command of trezorctl:

https://wiki.trezor.io/Using_trezorctl_commands_with_Trezor#Sign_message
