### ISSUE TITLE
Passphrase is asked multiple times, --cache-expiry-seconds is ignored

### ISSUE THREAD

**Issue by andrevmatos** [romanz/trezor-agent#284]
Passphrase cache is completely ignored. On both GPG and SSH agents, every time any operation is made, passphrase prompts comes up multiple (up to 3 or 4) times for a single operation. If the passphrase is empty, just hitting enter makes things go through, but this can be quite annoying.

Seems like the culprit is 2cb64991c3dc5530ccae8d239027a65fb3a001fd , since when `cached_passphrase_ack`, despite being set on the device instance, isn't used anymore in any other place in code.

**Comment by romanz** [comment]
Thanks for reporting the bug!
