### ISSUE TITLE
Signed Git merges do not require Trezor action (only pin entry)

### ISSUE THREAD

**Issue by AndrewIammatteo** [romanz/trezor-agent#287]
We have implemented signed commits and signed tags effectively. Now attempting to add a merge feature into our software, it seems to work perfectly, (signs and verified branch signatures before merging) but there is no action on the trezor that is required. It is required that the trezor is plugged in and the pin has been correctly entered. Has anyone attempted to implement merging in this same way?

**Comment by romanz** [comment]
Thanks for reporting this issue!
This is indeed quite strange... I couldn't reproduce this issue on my machine.
Does it reproduce on yours?

**Comment by romanz** [comment]
Ping :)
