### ISSUE TITLE
Ledger Nano X support

### ISSUE THREAD

**Issue by antonionardella** [romanz/trezor-agent#289]
Hello,

I am using the pip version of ledger_agent for my everyday ssh connections with the Ledger Nano S and it is awesome! I also wrote a guide in Italian to use the agent:
https://antonionardella.it/guida-passo-passo-chiavi-ssh-con-ledger-nano-s-in-gnu-linux/

I have a few questions:
is the support for the Ledger Nano X planned?
if yes, do you also expect to support the bluetooth connection?

Thank you very much!

**Comment by romanz** [comment]
Hello Antonio and thanks for the kinds words!

> is the support for the Ledger Nano X planned?

I don't have a Nano X device, but it seems that `ledgerblue` Python package (that `ledger_agent` uses) supports it: 
- https://github.com/LedgerHQ/blue-loader-python/commits/master.
- https://github.com/LedgerHQ/ledger-app-ssh-agent/commits/master

You can try the latest version (from GitHub) to see if it works for you :)

**Comment by jonathancross** [comment]
@ioiobzit Did that work for you?
