### ISSUE TITLE
Feature request: Make trezor-gpg keys deterministic.

### ISSUE THREAD

**Issue by ananteris** [romanz/trezor-agent#299]
trezor-gpg should probably be generating deterministic keys by default (e.g: trezor-gpg init --time=0) for a few reasons:

1) This is expected behavior for the rest of the Trezor ecosystem. 
2) It makes keys easily recoverable. 
3) It would have no effect on existing trezor-gpg keypairs
4) it has a very limited negative effect on security.

security implications:
Today, for an attacker to recreate a trezor-gpg private key they have to recover the seed, the password, the userid packet, and the time the key was created. Two of these (userid/time) can already be recovered if an attacker has intercepted the public key. Even without this however, the timestamp itself does not have enough entropy to protect the key more than just trivially and the effort of generating a key pair for a seed/pw/id combo for every possible timestamp is exponentially less secure than gpg itself.

**Comment by romanz** [comment]
Sounds good, thanks for the suggestion.
Please take a look at #300 PR.

**Comment by jonathancross** [comment]
Seems #300 was closed without being merged?

**Comment by jrruethe** [comment]
If I understand this correctly, it means that using only the seed, the Trezor will generate the exact same GPG Master key?
Does this apply to subkeys as well?

For example, if I were to wipe then restore my seed onto a Trezor and regenerate the master key, then 3 subkeys (auth, sign, encrypt), that those 3 subkeys would be identical to the ones I had before wiping, such that I can still use the subkey to decrypt files that were previously encrypted by the subkey before wiping?

Are there any settings or options that I need to make sure I set the same? I imagine I need to use the same email address?

**Comment by attila-lendvai** [comment]
@romanz would it be possible (and desirable) for the GPG key indeed having a creation time (i.e. not printing 1970-01-01), but be deterministic?

IOW, fix this not by defaulting `--time` to `0`, but by not including the creation time in the seed of the key?

**Comment by romanz** [comment]
IIRC, key creation timestamp is part of the signed data when creating the key - so I think the resulting GPG key depends on its value:
https://github.com/romanz/trezor-agent/blob/338a075ed500f210a707cb3adf90104602e35c48/libagent/gpg/encode.py#L20

**Comment by romanz** [comment]
BTW, it's possible to set creation time to any other timestamp using the relevant epoch time, e.g.:
```
$ date --date='@1630000000'
Thu 26 Aug 2021 20:46:40 IDT
```

**Comment by attila-lendvai** [comment]
> IIRC, key creation timestamp is part of the signed data when creating the key - so I think the resulting GPG key depends on its value:

indeed, it must be part of the hashed area: https://datatracker.ietf.org/doc/html/rfc4880#section-5.2.3.4
