### ISSUE TITLE
wish: use trezor as hardware gpg agent

### ISSUE THREAD

**Issue by tphyahoo** [romanz/trezor-agent#3]
is this on the roadmap?

it would be totally awesome?

would anything be required from libgpg?

side note: as with the bitcoin keys, everything is recoverable if you have passphrase... right?

this would compete with (trapped forever in dev mode?)

http://trilema.com/2013/snsa-first-product-the-cardano/

Ideally, the trezor would never leak keys, even on a compromised computer.  Actually I don't know if that's possible with the computing power on trezor.  I guess signing hashes should be fine, but I don't kow if there is enough power there to encrypt/decrypt.  Even just signatures would be great though, and it would be great advertisement for trezor.  

In practice, I think authentication matters more than secrecy these days.  (Look at what happened with bitpay heist because they weren't signing their emails.)

**Comment by romanz** [comment]
This is actually a very good idea!

The only problem is that the default GPG version is v2.0 on my machine, and it does not support any ECDSA yet. I will take a look at v2.1 which should support NIST-256 curve:
https://www.gnupg.org/faq/whats-new-in-2.1.html#ecc

**Comment by tphyahoo** [comment]
Glad you like the idea.

Can you say whether agent leaks privkeys on hacked computer?

I don't know enough about ssh agent / gpg agent to answer this myself.

**Comment by jhoenicke** [comment]
No, trezor-ssh-agent doesn't leak the private key.  It sends the challenge to the Trezor, the signature is computed on the Trezor and send back to the PC.  So the private key never leaves the Trezor.

The same would hold for gpg.  I'm not sure how gpg-agent works and if something similar is possible.  Also Trezor only supports  AES + ECDH for encryption and I know too little about gpg to say whether one can restrict the encryption algorithms for a key.  The encrypted messages would probably leak to the computer, since the display is too inconvenient to view the message.  Also when signing a message the display is not big enough to view the signed contents.

**Comment by jhoenicke** [comment]
If ecdsa is only supported with gpg 2.1, this also means that your communication partners need to install gpg 2.1 to send you encrypted messages or to check your signatures.  Of course, you can have several sub keys and use the Trezor-based key only when your peer supports it.

**Comment by tphyahoo** [comment]
> The decrypted messages would probably leak to the computer

right... so... 

add an hdmi out to trezor v2.

get one of these:

http://www.amazon.com/Sewell-Direct-Ibis-Bi-Directional-Passthrough/dp/B00629NHW6/ref=sr_1_2?ie=UTF8&qid=1445373643&sr=8-2&keywords=sewell+hdmi+splitter&refinements=p_89%3ASewell+Direct

Press the button to read the decrypted messages:

http://ecx.images-amazon.com/images/I/51%2B3Uiwmi6L._SL1000_.jpg

(ha ha only serious...)

**Comment by romanz** [comment]
https://gist.github.com/vt0r/a2f8c0bcb1400131ff51

**Comment by romanz** [comment]
http://unix.stackexchange.com/questions/188668/how-does-gpg-agent-work

**Comment by romanz** [comment]
https://www.gnupg.org/howtos/card-howto/en/ch01.html
http://g10code.com/docs/openpgp-card-3.0.pdf
https://tools.ietf.org/html/rfc6637

**Comment by romanz** [comment]
@tphyahoo Please take a look :)

**Comment by tphyahoo** [comment]
wow, this is great!

**Comment by tphyahoo** [comment]
can there be encryption as well as signing?

**Comment by romanz** [comment]
It should work (in theory) - but I guess that it will probably require a few more changes to the TREZOR firmware, so currently I focus on the signature part.

**Comment by romanz** [comment]
Using the TREZOR for ECDH decryption:
https://github.com/trezor/trezor-mcu/issues/85

**Comment by romanz** [comment]
Please take a look :)
https://gist.github.com/romanz/3c1617e8dd5e6c67035e22e1c73ab4d5
