### ISSUE TITLE
Using Trezor from remote server

### ISSUE THREAD

**Issue by marza91** [romanz/trezor-agent#312]
Hello,

I've just managed to set up trezor-agent, and everything works flawlessly except for one use case:

I have a remote linux server i remote into using trezor-agent, and I have added a public key to my github account. Both connections works fine from my local machine, but I would also like to be able to access github when working through the remote machine, with the trezor device connected to a local usb port. Is it somehow possible to forward or send ssh authentication calls between my local and remote machine, so that i can for instance run "git push" and "git pull" on the remote machine and authenticate with the local trezor device? I hope i'm making sense, if not I can try to make an illustration :smile:

**Comment by romanz** [comment]
Thanks for opening this issue and sorry for the delayed response.
I think that you may solve it by using "agent frowarding" as described here:
https://developer.github.com/v3/guides/using-ssh-agent-forwarding/

Please let me know if it works for you.

**Comment by marza91** [comment]
Oh, I did not know about this feature, but it worked like a charm! Thank you very much!

**Comment by romanz** [comment]
You're welcome :)
