### ISSUE TITLE
[Question] Can SSH use the trezor-gpg-agent like it can for the gpg-agent? 

### ISSUE THREAD

**Issue by doolio** [romanz/trezor-agent#324]

**Comment by romanz** [comment]
In order to use Trezor for SSH authentication, I suggest using `trezor-agent` from CLI:
[![asciicast](https://asciinema.org/a/22959.svg)](https://asciinema.org/a/22959)

**Comment by doolio** [comment]
Ok, undestood. Maybe, it could be a feature for a future release?

Thanks for your time.
