### ISSUE TITLE
trezor-gpg unlock error

### ISSUE THREAD

**Issue by rishanb** [romanz/trezor-agent#328]
Hi, once I've initialized a key I restart Ubuntu 18.04.
`gpg2-k`
shows my public key and confirms we are looking at: 
> /.gnupg/trezor/pubring.kbx

If I open gpa, it does not prompt me to unlock my Trezor and does not find the private key.

Trying:
`trezor-gpg unlock`
I get the following error:
>trezor-gpg unlock
Traceback (most recent call last):
  File "/home/relax-lts/.local/bin/trezor-gpg", line 11, in <module>
    sys.exit(gpg_tool())
  File "/home/relax-lts/.local/bin/trezor_agent.py", line 6, in <lambda>
    gpg_tool = lambda: libagent.gpg.main(DeviceType)
  File "/home/relax-lts/.local/lib/python3.6/site-packages/libagent/gpg/__init__.py", line 322, in main
    seconds=float(args.cache_expiry_seconds))
AttributeError: 'Namespace' object has no attribute 'cache_expiry_seconds'

**Comment by rishanb** [comment]
fwiw, tried this on a fresh install on Lubuntu 20.04 and seeing the same issue:
>t3st@t3st-lubuntu:~$ trezor-gpg unlock -v
Traceback (most recent call last):
  File "/home/t3st/.local/bin/trezor-gpg", line 8, in <module>
    sys.exit(gpg_tool())
  File "/home/t3st/.local/bin/trezor_agent.py", line 6, in <lambda>
    gpg_tool = lambda: libagent.gpg.main(DeviceType)
  File "/home/t3st/.local/lib/python3.8/site-packages/libagent/gpg/__init__.py", line 322, in main
    seconds=float(args.cache_expiry_seconds))
AttributeError: 'Namespace' object has no attribute 'cache_expiry_seconds'

Let me know if there is any log file that could help identify the issue or if there is anything else I can do to provide more information.

**Comment by romanz** [comment]
Thanks for reporting the issue!
I am planning to test it soon - could you please describe which `trezro-agent` version are you using/installing?

**Comment by romanz** [comment]
BTW, does Trezor-based SSH agent work for you?

**Comment by rishanb** [comment]
`trezor-agent --version` gives me:
>trezor-agent=0.11.0 libagent=0.14.0

Tbh I haven't attempted use of the SSH agent, however after reproducing the above-reported error, if I run:
`trezor-agent unlock` (which I'm assuming unlocks the Trezor for SSH usage) I get:
>ecdsa-sha2-nistp256 XXXXXXXXXXX <ssh://unlock|nist256p1>
with no error, and assume that it is working fine.

**Comment by romanz** [comment]
Good catch, thanks!
Indeed, the `trezor-gpg unlock` was broken.
It should be fixed by https://github.com/romanz/trezor-agent/commit/52d840cbbb5a097c16b7a09932ef78c17aa78f20.

**Comment by rishanb** [comment]
Thanks, I'm guessing the update hasn't been pushed yet?
Github newbie - Let me know if I should be downloading the fix somehow and testing.
I tried:
`pip3 install -U trezor-agent`
and had the same issue,
`trezor-agent --version` gives me the same versions as before:
>trezor-agent=0.11.0 libagent=0.14.0

**Comment by romanz** [comment]
Released a new version: https://pypi.org/project/libagent/0.14.1/

**Comment by romanz** [comment]
You can update using `pip3 install -U libagent`.

**Comment by rishanb** [comment]
Thank you, make progress one minor hiccup/potential improvement for later?

After updating was able to unlock via terminal successfully using:
`trezor-gpg unlock`

Then:
`gpg -k` shows correct key and confirms the correct path is working as expected.

Then:
`gpa` opens, shows the key, but doesn't recognize that we have the private key on the unlocked Trezor.
It says:
"You do not have a private key yet...." while showing the key attached to the Trezor in the background.
