### ISSUE TITLE
systemd error trying to parse service type

### ISSUE THREAD

**Issue by doolio** [romanz/trezor-agent#329]
It's probably trivial as even when the error was present my trezor still functioned. In any case, I wanted to bring it to your attention. Creating and using the `trezor-gpg-agent.service` as described in the [README](https://github.com/romanz/trezor-agent/blob/master/doc/README-GPG.md#start-the-agent-as-a-systemd-unit) I noticed the following systemd error:

> /home/doolio/.config/systemd/user/trezor-gpg-agent.service:6: Failed to parse service type, ignoring: Simple

Changing the type to [simple](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Options) and the error no longer appears so it seems the service type value is case sensitive. But like I said despite the error the `trezor-gpg-agent` still worked.

Thanks for your time.

**Comment by romanz** [comment]
Many thanks, it should be fixed at 4d9d6c0.
