### ISSUE TITLE
pypi version is still 0.11.0

### ISSUE THREAD

**Issue by chenrui333** [romanz/trezor-agent#331]
Not sure if it is intentional, but feel necessary to call it out the pypi version is still v0.11.0 (while the most latest tagged commit is 0.14.1). Thanks!

**Comment by romanz** [comment]
It's a bit confusing, but the core library is released under [`libagent`](https://pypi.org/project/libagent/), while the hardware-specific packages are released separately (e.g. [`trezor-agent`](https://pypi.org/project/trezor-agent/)).

See here for more details:
https://github.com/romanz/trezor-agent/pull/301/files
