### ISSUE TITLE
[Question] What’s the correct workflow to use?

### ISSUE THREAD

**Issue by Flink** [romanz/trezor-agent#34]
Hi!

I’m just trying to use my TREZOR as a SSH agent and I find it really difficult to actually use it for this. Everytime I’m using `trezor-agent` or `trezor-git` it asks me for my PIN and then to confirm the use on the TREZOR. So how is it usable on a day-to-day basis?
What am I missing here?

Thanks :)

**Comment by romanz** [comment]
Thanks for reporting this issue!
It was happening due to the following call to `clear_session()`:
https://github.com/romanz/trezor-agent/commit/bf598435fb3a4075d7ff0de7d69c6137cb96b374#diff-aea63b272e483857ce8fac4c1adf6813L38

After the fix above, the devices would require a single PIN entry during a session of multiple SSH commands. It would still require manual confirmation for each SSH authentication, to make sure you are connecting to the right host.

**Comment by Flink** [comment]
@romanz Ok cool! And is it possible for the trezor-agent to manage multiple identities at once? (like a normal ssh-agent)

**Comment by romanz** [comment]
Yes, you can use different SSH identities - e.g. by using the following aliases:
```
$ alias git_hub='trezor-agent -v -e ed25519 git@github.com -- git'
$ alias git_lab='trezor-agent -v -e ed25519 git@gitlab.com -- git'
$ git_hub push  # using GitHub's SSH identity
$ git_lab push  # using GitLab's SSH identity
```

**Comment by Flink** [comment]
@romanz So that’ll work because it’s a one time operation it seems. I just tried to use `trezor-agent -c` to two different machines (so with different identities) in two tabs in tmux and while a connection is established to one of the machine, the second one can’t be established because of this error:
```
2016-09-28 18:41:48,045 ERROR     Connection error: open failed      [__main__.py:126]
```

**Comment by romanz** [comment]
No problem :)
IIUC it seems that even trezorctl does not allow to simultaneously opening two connections to the TREZOR... 
@prusnak Is there a way to concurrently use the TREZOR from two separate processes from Python?

**Comment by romanz** [comment]
I guess that the correct way is opening a connection to the TREZOR on demand, and not using a long-lived connection, which is preventing other Python-based apps to use the TREZOR.

**Comment by romanz** [comment]
Fixing this issue will be tracked by #68.
