### ISSUE TITLE
Trezor agent installation instructions confusing

### ISSUE THREAD

**Issue by doolio** [romanz/trezor-agent#342]
Is it `trezor_agent` or `trezor-agent`? Note the underscore vs the hyphen. I believe it is the latter.

<img width="346" alt="trezor-agent-install-instructions" src="https://user-images.githubusercontent.com/13859009/102245727-cfd9d000-3ef5-11eb-85cf-17b313bf69e8.PNG">

Step 3 above suggests using `$ pip3 install trezor_agent` but PyPI suggests `$ pip 3 install trezor-agent`. This [link](https://github.com/romanz/trezor-agent/blob/fd182e744fdafd24c3f8f27742d69e8ea6fbf2b1/doc/INSTALL.md#L66) also uses `trezor_agent` but is any case re-directed to [trezor-agent](https://pypi.org/project/trezor-agent/).

There is reference to `trezor_agent` [here](https://github.com/romanz/trezor-agent/blob/d0e7fa7ccade614f8b4285a2eb373db553535557/agents/trezor/setup.py#L5), [here](https://github.com/romanz/trezor-agent/blob/d0e7fa7ccade614f8b4285a2eb373db553535557/agents/trezor/setup.py#L11) and [here](https://github.com/romanz/trezor-agent/blob/d0e7fa7ccade614f8b4285a2eb373db553535557/agents/fake/setup.py#L10).

Also, is this line `$ pip3 install Cython hidapi` necessary considering `trezor[hidapi]` is required in the trezor agent [setup.py](https://github.com/romanz/trezor-agent/blob/d0e7fa7ccade614f8b4285a2eb373db553535557/agents/trezor/setup.py#L14) and you don't suggest it if installing from this repository. I believe `Cython` (or `cython` and/or `cython3` to be explicit?) is a [pre-requisite of trezor](https://github.com/trezor/trezor-firmware/tree/master/python#installation-options) so is it not less confusing to list it as an OS dependency.

**Comment by romanz** [comment]
Thanks!
It's possible to install it both using `pip install trezor_agent` & `pip install trezor-agent`.
I'll modify the docs to use `trezor-agent` for consistency.

**Comment by doolio** [comment]
> It's possible to install it both using `pip install trezor_agent` & `pip install trezor-agent`

Interesting, why is that? 

> I'll modify the docs to use `trezor-agent` for consistency.

Looking at this again because I wanted to see if it was necessary to update the following line:

https://github.com/romanz/trezor-agent/blob/3c911e99a0394278104564092225d67c75e74b99/agents/trezor/setup.py#L5

It seems not as despite the PyPi page pointing to https://pypi.org/project/trezor-agent the source distribution visible on this [page]( https://pypi.org/project/trezor-agent/#files) uses `trezor_agent` so I think on further reflection the best think would have been to update the PyPi project page to be https://pypi.org/project/trezor_agent and to use `trezor_agent` throughout that page. This keep it consistent with your other hardware device agent packages on PyPi - they all use an underscore except for `onlykeep-agent` but it is at least consistent to always use a hypen everywhere.
