### ISSUE TITLE
gpg: can't connect to the agent: IPC connect call failed

### ISSUE THREAD

**Issue by bereska** [romanz/trezor-agent#343]
can't get gpg work after upgrading to Big Sur macOS
ssh part works just fine
```
MacBook-Air-DG-4007:~ bereska$  export GNUPGHOME=~/.gnupg/ledger
MacBook-Air-DG-4007:~ bereska$ gpg -d test5.gpg
gpg: can't connect to the agent: IPC connect call failed
```

**Comment by bereska** [comment]
MacBook-Air-DG-4007:~ bereska$ gpg --version
gpg (GnuPG) 2.2.23
libgcrypt 1.8.6
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /Users/a0000/.gnupg/ledger
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2

**Comment by romanz** [comment]
Does it reproduce with https://github.com/romanz/trezor-agent/tree/master/agents/fake?

**Comment by bereska** [comment]
hi @romanz, do i need to run these two scripts without my ledger plugged in? do i need to modify the scipts since i use ledger-agent not trezor-agent? thank you

**Comment by romanz** [comment]
You should run `ledger-gpg init` - see the documentation here:
https://github.com/romanz/trezor-agent/blob/master/doc/README-GPG.md

**Comment by bereska** [comment]
ok, my bad, it's all good now. I just renamed 'ledger' folder and ran 'ledger-gpg init' with the original timestamp again and gpg is back in business)
what do you think caused it? macOS upgrade or ledger firmware upgrade? I did both at the same time
thank you

**Comment by romanz** [comment]
Happy it worked out :)

> what do you think caused it? 

Good question, I don't know...

**Comment by bereska** [comment]
it's ok)
thank you for maintaining your great tool!
