### ISSUE TITLE
How to delete private keys from trezor?

### ISSUE THREAD

**Issue by brianveltman** [romanz/trezor-agent#348]
Hi,

I've been playing around with this trezor-agent, created a dozen of keys, just to trial and error and understand its workings.
Now I'm curious how to delete those generated keys from trezor?

**Comment by Senjuu** [comment]
You cannot delete private keys from your trezor, as there are no private keys to delete. On your trezor there is only one private secret. That is your master secret, which is backed-up by your seedphrase. The private keys you want to delete are derived from this master secret in a way that if your trezor gets brocken or lost, you only need to reenter your seedphrase in a new trezor to regain access to the private keys linked to your public keys.

For further information please take a look at: [Trezor Wiki: Hierarchical Deterministic Wallet](https://wiki.trezor.io/Hierarchical_deterministic_wallet)
