### ISSUE TITLE
Why limit one identity to one host?

### ISSUE THREAD

**Issue by lukechilds** [romanz/trezor-agent#364]
From https://github.com/romanz/trezor-agent/blob/020572ef5f7bab8767efa1403da1ac0e919b29ce/doc/README-SSH.md#3-connect-to-a-server-directly-via-trezorkeepkeyledgeronlykey-agent: 

>The identity user@remotehost is used as both the destination user and host as well as for key derivation, so you must generate a separate key for each host you connect to.

Is there a reason for this? For my use case I'd like to have a single identity I use for all hosts. I can do this with:

```
$ trezor-agent my-identity --shell
$ ssh foo@bar
```

But I'd like to be able to do something simpler like:

```
$ trezor-agent my-identity --connect foo@bar
```

so I could even add some kind of alias like:

```
alias trezor-ssh="trezor-agent my-identity --connect"
```

which could be used like:

```
$ trezor-ssh foo@bar
```

Is there a reason this is not the case? I feel like maybe I'm misunderstanding something about the intended use case.

**Comment by romanz** [comment]
Many thanks for the question!
The main reason is that it allows better privacy - each host knows only its own public key.
Also, if somehow a single private key is leaked, the damage will be contains to a single host.

I agree that it is more complex to manage, so you can use the following command:
```
$ trezor-agent my-identity -- ssh foo@bar
```

**Comment by romanz** [comment]
> I'm correct in thinking it's not possible to export the privkeys via the API right? 

Yes :)
