### ISSUE TITLE
issuer does not match any User ID

### ISSUE THREAD

**Issue by iv-nn** [romanz/trezor-agent#380]
When verifying a signature made by my trezor gpg key I get the following output:

> gpg: Signature made Mon 28 Feb 2022 11:41:08 PM CET
> gpg:                using ECDSA key 2C9AB3947BF7BEFED1E80CBF319B7F98E9A3A3B8
> gpg:                issuer "test@example.com"
> gpg: Good signature from "Test <test@example.com>" **[uncertain]**
> **gpg: issuer "test@example.com" does not match any User ID**
> **gpg: WARNING: The key's User ID is not certified with a trusted signature!**
> **gpg:          There is no indication that the signature belongs to the owner.**
> Primary key fingerprint: 2C9A B394 7BF7 BEFE D1E8  0CBF 319B 7F98 E9A3 A3B8
> gpg: WARNING: not a detached signature; file '1' was NOT verified!

I don't understand the bold part. What's with the issuer not matching any User ID?
I'll admit I'm not really savvy with GPG, so I've probably missed something, but I don't have this issue with my old, non trezor, key.

I'm using the following version:
```
$ trezor-agent --version
trezor-agent=0.11.0 libagent=0.14.4
```

And I've set it up according to [README-GPG.md](https://github.com/romanz/trezor-agent/blob/e4d16a361aaeb15ff3f7bc5d9d0b891eb87b2dbe/doc/README-GPG.md):
```
$ trezor-gpg init "Test <test@example.com>" # tried with and without -e ed25519
$ export GNUPGHOME=~/.gnupg/trezor
$ touch 1
$ gpg --output 1.sig --sign 1
$ gpg --verify 1.sig
```

**Comment by iv-nn** [comment]
Also gpg version in case that's relevant :

```
$ gpg --version     
gpg (GnuPG) 2.3.3
libgcrypt 1.9.4
```

Has anyone experienced anything similar? Could this be unrelated to trezor-agent and just be a case of bad configuration somewhere else?

**Comment by drizzt** [comment]
You need to mark the key as primary, so:
gpg --edit-key test@example.com
1
primary
save

**Comment by iv-nn** [comment]
That was it. Thanks !
