### ISSUE TITLE
Support for a passphrase?

### ISSUE THREAD

**Issue by Midar** [romanz/trezor-agent#381]
Given that the Trezor hardware is vulnerable to voltage glitching which allows easy recovery of the secrets, is there a way to add a passphrase to GPG keys, similar to https://wiki.trezor.io/Passphrase?

**Comment by Yuxanju** [comment]
That’s why it’s important you synchronize your hardware wallet and then you debug it

**Comment by Midar** [comment]
???

I'm talking about this: https://blog.kraken.com/post/3662/kraken-identifies-critical-flaw-in-trezor-hardware-wallets/

Trezor's official statement was that it's not too bad because you can use a passphrase to protect your wallet. However, you'd also need a passphrase then to protect your GPG keys, otherwise the same attack would work against GPG keys on a Trezor.

**Comment by Yuxanju** [comment]
Just synchronize your wallet and debug it

**Comment by Midar** [comment]
??

What do you mean by "synchronize your wallet"? What is that even supposed to mean in the context of *GnuPG*?!

And what should I debug here - how do you "debug" that absence of a feature?!

**Comment by romanz** [comment]
If a passphrase usage is enabled, it will be used to derive the GPG secret key.
