### ISSUE TITLE
How about using `cryptography` library?

### ISSUE THREAD

**Issue by dekoza** [romanz/trezor-agent#39]
https://cryptography.io/

What do you guys think about this lib? Would it be helpful? Maybe it could simplify the code? I'm digging into it :smiley:

**Comment by romanz** [comment]
Thanks for the heads up :)
I was using `ecdsa` and `ed25519` Python packages mainly for parsing elliptic curve public keys, and validating signatures (before the firmware implementation was ready). 
However, it seems that currently `cryptography` package does not support NIST256 and Ed25519 curves...
