### ISSUE TITLE
[Ledger] New SSH app requirements

### ISSUE THREAD

**Issue by cbouvet-ledger** [romanz/trezor-agent#414]
Hello @romanz,

We have fixed an issue in the Ledger SSH app (https://github.com/LedgerHQ/app-ssh-agent/issues/38#issue-1517502869) that requires a modification on your side to make it work.

Indeed, the last packet you send (in a ssh sign blob request) to the Ledger device needs its p1 to be |= 0x80.
(https://github.com/LedgerHQ/app-ssh-agent/pull/37/commits/7d9a507cba23aed93af9aacdc8a6b36e870b4c8e)

We will release the new app as 0.0.8. You can use the get version APDU (B001000000) to handle both before and after the modification.

Best regards,

**Comment by romanz** [comment]
Many thanks for the heads-up @cbouvet-ledger!

As I am not familiar enough with the Ledger APDU-based protocol (initially added in https://github.com/romanz/trezor-agent/commit/adb09cd8ca79d1906843c915bb48cfde978c266c), I would grateful if you could please contribute a PR for this issue in [libagent/device/ledger.py](https://github.com/romanz/trezor-agent/blob/master/libagent/device/ledger.py).
I would be happy to assist with review :)

**Comment by cbouvet-ledger** [comment]
oh BTChip did that, I had no idea! Will update it then :bow:

**Comment by cbouvet-ledger** [comment]
https://github.com/romanz/trezor-agent/pull/415 should do the job. tested on nanos with both 0.0.7 (old format) and 0.0.8 (new format)

**Comment by romanz** [comment]
Many thanks!

**Comment by cbouvet-ledger** [comment]
fixed in https://github.com/romanz/trezor-agent/pull/415 !

**Comment by cbouvet-ledger** [comment]
Hello @roman,
can/have you redeploy the ledger agent on PyPi with my modifications?

Thanks in advance !

**Comment by cbouvet-ledger** [comment]
hello @romanz ,

i've found a small issue and i'm working on fixing it!

**Comment by romanz** [comment]
Many thanks - merged the fix and release https://pypi.org/project/libagent/0.14.7/ :)
