### ISSUE TITLE
Add instructions to README on how to update

### ISSUE THREAD

**Issue by doolio** [romanz/trezor-agent#425]
As the title suggests. It has been sometime since I installed `trezor-agent` what are the steps I need to follow if I want to update it. I have two machines where I use it one running Parabola and the other Debian 11 (Bullseye).

Thanks for your time and this package.

**Comment by romanz** [comment]
It should be OK to use `pip install -U trezor-agent`.

**Comment by romanz** [comment]
How did you installed in the beginning?

**Comment by doolio** [comment]
Thanks. It has been sometime (see issue #342) but I believe it was the same command minus the `-U` option.

However, this installs v0.12.0 from PyPi but the last tagged version here is v0.14.7. But perhaps that does not mean it is ready for a release to PyPi?

**Comment by romanz** [comment]
We use different versioning for [TREZOR-specific package (currently 0.12.0)](https://pypi.org/project/trezor-agent/) and the [generic SSH agent library (currently at 0.14.7)](https://pypi.org/project/libagent/). 
You can check the installed versions using `pip freeze | grep agent`.
