### ISSUE TITLE
Add Binary/Pre-built Assets

### ISSUE THREAD

**Issue by Pandapip1** [romanz/trezor-agent#427]
I use Anaconda for package management. As such, it is impossible for me to ensure that the trezor-agent package is always loaded. Could a binary be provided?

**Comment by romanz** [comment]
Is it possible to use `pip install` to install `trezor-agent` from source?

**Comment by Pandapip1** [comment]
Yes, but if I then switch my conda environment to anything other than the base environment (which is a lot of the time), then it isn't. Also:

1. The base environment should be kept as small as possible
2. Using pip to install packages in conda environments is an anti-pattern
3. If conda isn't loaded, then the trezor-agent binary won't be in the path

**Comment by romanz** [comment]
I can suggest installing `trezor-agent` in a separate virtualenv, so you can start it with:
```
$ python3 -m venv ~/tmp/venv
$ ~/tmp/venv/bin/pip install trezor-agent
$ ~/tmp/venv/bin/trezor-agent --help
usage: trezor-agent [-h] [-v] [--version] [-e CURVE] [--timeout TIMEOUT] [--debug] [--log-file LOG_FILE] [--sock-path SOCK_PATH] [--pin-entry-binary PIN_ENTRY_BINARY] [--passphrase-entry-binary PASSPHRASE_ENTRY_BINARY] [--cache-expiry-seconds CACHE_EXPIRY_SECONDS]
                    [-d | -f | -s | -c | --mosh]
                    identity [ARGUMENT ...]
```

**Comment by Pandapip1** [comment]
How hard would it be to add a build step to the CI?

(Honest question - if it would be difficult, feel free to close this issue)

**Comment by romanz** [comment]
Not sure what do you mean by a build step... what is the artifact you expecting to get?

**Comment by Pandapip1** [comment]
I would expect a .exe file that spawns the daemon, for Windows at least.

**Comment by romanz** [comment]
Currently this project doesn't support Windows.

**Comment by romanz** [comment]
https://github.com/romanz/trezor-agent/pull/362

**Comment by romanz** [comment]
Closing, since I am not sure how make the Windows binaries' build process deterministic.
