### ISSUE TITLE
Repository description does not mention age considering it is now supported

### ISSUE THREAD

**Issue by doolio** [romanz/trezor-agent#433]
Maybe add some new description tags as well?

Should it also state GPG rather than PGP or at least OpenPGP?

**Comment by romanz** [comment]
Feel free to open a PR :)

**Comment by doolio** [comment]
Will do. I didn't think I could submit a PR for a change to the repository description but only to changes to files within the repository.

**Comment by doolio** [comment]
As I thought I cannot submit a PR for changing the repository description on my fork. I also don't see any topic tags on my fork like you have here.

**Comment by romanz** [comment]
My bad, will update the description.
