### ISSUE TITLE
Please enable discussions

### ISSUE THREAD

**Issue by SlugFiller** [romanz/trezor-agent#447]
I sometimes want to discuss PRs that I'm working on, or planning. Things like design choices, issues I'm facing, possible issues or irritations I'm finding in the code base, or even the choice of which PR to work on next.

The thing is, none of these questions amount to an issue, since it's not a request to fix something. It's, at best, a question. And at worst, little more than a comment.

At the same time, even if it's related to a PR in progress, it does not amount to a PR, or even a PR draft, as such questions could arise before the PR has any significant amount of code.

All of these cases are appropriate for GitHub's relatively new Discussions feature, which allows opening a conversation that's neither an issue, nor a PR. It would also be a good place to concentrate the various support questions pretending to be issues that occasionally crop up, and have a high rate of duplicates (See the amount of ambiguously identical issues regarding subkeys).

**Comment by romanz** [comment]
https://github.com/romanz/trezor-agent/discussions are enabled
