### ISSUE TITLE
[Suggestion] Use concurrency tag for GitHub workflows

### ISSUE THREAD

**Issue by SlugFiller** [romanz/trezor-agent#448]
If you add:
```
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
```
to the workflow script, it will make it so a push or force-push to a PR branch will cancel the workflow run of previous pushes. This is useful, because the result of a previous run is useless if it's no longer part of the PR. There's no reason to keep it running, even if each run is not particularly long.

**Comment by romanz** [comment]
LGTM - could you please open a PR?

**Comment by romanz** [comment]
Thanks, merged https://github.com/romanz/trezor-agent/pull/449.
