### ISSUE TITLE
GPG operations fail PIN entry

### ISSUE THREAD

**Issue by guruvan** [romanz/trezor-agent#45]
Using latest from master & trezor 0.7.5 I'm unable to perform any gpg operations requiring a pin

this command
 ```
 ./cmdtr.py sign_message -n "44'/0'/0'/0/0" "testing 123"
 ```
produces a usable, and different, not echoed to the terminal pinentry than when I run 
 ```
 export TREZOR_GPG_USER_ID=me@id.gpg
 trezor-gpg -v agent 
 echo "sign this" | gpg2 --sign
 ```
 Which uses some other method which echoes the pin (scrambled, of course) to the terminal - since scramble this is ok, but this will not accept an  ```enter``` key - so doesn't allow the pin to be entered for signing

**Comment by romanz** [comment]
Thanks for reporting this issue!

**Comment by romanz** [comment]
This bug happens since the PIN entry should be handled by `trezor-gpg agent` process, which is running in the background.
`trezor-gpg` requests the PIN but cannot read it from stdin (since it's not the foreground process), so the entered scrambled PIN is written to `gpg`'s stdin instead.

**Comment by romanz** [comment]
As a temporary workaround, you can launch the `trezor-gpg agent` process in a separate window (in foreground mode - without the trailing `&`), so the PIN entry could be done there (separately from the GPG signing/decryption processes).

**Comment by romanz** [comment]
The easiest solution for now will be to add an "unlock" operation when starting [gpg-shell](https://github.com/romanz/trezor-agent/blob/master/scripts/gpg-shell).

**Comment by romanz** [comment]
```
$ trezor-gpg-unlock -v
Use the numeric keypad to describe number positions. The layout is:
    7 8 9
    4 5 6
    1 2 3
Please enter current PIN: 

2016-10-30 22:10:26,094 INFO         unlocked Trezor device
```

**Comment by guruvan** [comment]
Thanks @romanz I'll get this updated and give the new command a go! 👍
