### ISSUE TITLE
Trezor session can't be reset if trezor-aegnt crashes or is killed during input

### ISSUE THREAD

**Issue by SlugFiller** [romanz/trezor-agent#451]
If you are asked for a pin or confirmation on the device, and then trezor-agent is killed (even with SIGINT, but certainly after SIGKILL), the query remains open. That's fine. That's after the program has exited.

The problem is, when you next run trezor-agent, you get errors like:
```
trezorlib.exceptions.TrezorFailure: PinCancelled: PIN entry cancelled
```
```
RuntimeError: Got <class 'trezorlib.messages.Features'>, expected <class 'trezorlib.messages.Address'>
```
```
trezorlib.exceptions.TrezorException: Unexpected response to Initialize
```

In other words, the device or driver isn't aware that the session ended, and it's not opening a new session. The only way to fix this is to unplug and replug the physical device.

Preferably, there should be a way to detect this, and tell the device to kill the previous session and start a new one. If possible, this should even cancel any in-progress confirmation message, if it's still open.

**Comment by romanz** [comment]
Could you please record the shell during the issue reproduction (e.g. with https://asciinema.org)?
BTW, which device are you using?

Regarding session management, TREZOR uses the following logic:
https://github.com/trezor/trezor-firmware/blob/master/docs/common/communication/sessions.md
In libagent, there is the following caching behavior:
https://github.com/romanz/trezor-agent/blob/135e2f5b8e11bb79a40279f9bf0bdfaf6acb9dcf/libagent/device/trezor.py#L78

**Comment by SlugFiller** [comment]
This can be closed, since I was able to replicate the bug in TrezorSuite. i.e., if you kill the program (e.g. with task manager) while the device is waiting for input (e.g. allow labels), and run it again, it fails to communicate with the device until it is unplugged and replugged. So, for all intents and purposes, this is "intended behavior".
