### ISSUE TITLE
missing new releases on pypi

### ISSUE THREAD

**Issue by chenrui333** [romanz/trezor-agent#494]
👋 looks like the new releases' sdist files are not on pypi. Thanks!

**Comment by romanz** [comment]
Which release is missing?

- https://pypi.org/project/libagent/0.15.0/ is the last common "agent" package release (https://github.com/romanz/trezor-agent/blob/f1fe7b516253d9ff3c3a0edc4d6b93a329d4b64e/setup.py#L6)
- https://pypi.org/project/trezor-agent/0.12.0/ is the last TREZOR-specific package (https://github.com/romanz/trezor-agent/blob/f1fe7b516253d9ff3c3a0edc4d6b93a329d4b64e/agents/trezor/setup.py#L6).

**Comment by romanz** [comment]
Ping :)

**Comment by chenrui333** [comment]
aha, that makes sense. thanks!!

**Comment by chenrui333** [comment]
might be good to differentiate in the git tags, I got confused a bit :)

<img width="469" alt="image" src="https://github.com/user-attachments/assets/ea965f1a-771e-4f73-8aba-874a4942eccd" />

**Comment by romanz** [comment]
Will do, thanks for the heads-up :)
