### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by keynan** [romanz/trezor-agent#5]
My understanding is this is an official Trezor code base

When the device ships it says ~$25 for hardware ~$75 for "security services"

How about those services include an easy install. If I have to hot patch pip this is not an acceptable release path for paid for software.

**Comment by romanz** [comment]
This repository is my own open source project, and I am not part of the SatoshiLabs team.

Having said that, I would be happy to help to improve the installation experience of this tool.
Could you please elaborate which problems have you encountered while installing trezor-agent?
Why did you have to patch pip for this?

**Comment by romanz** [comment]
@keynan I would be happy to help but I need more information.

**Comment by romanz** [comment]
@keynan please reply so we could fix this issue.

**Comment by romanz** [comment]
No reply from OP.
