### ISSUE TITLE
cannot open more than one session

### ISSUE THREAD

**Issue by fansari** [romanz/trezor-agent#62]
I found your explanation how to use multiple sessions with a sub shell.

https://asciinema.org/a/33240

For me this does not work. First of all I have to export  SSH_AUTH_SOCK and SSH_AGENT_PID before I can do "ssh-add -L".

After I have done this I can ssh a host from this window or open another Gnome terminal and ssh from there.

But: once one connection is opened I cannot open a second one.

Logfile from ssh: [ssh.txt](https://github.com/romanz/trezor-agent/files/545864/ssh.txt)

**Comment by fansari** [comment]
[ssh.txt](https://github.com/romanz/trezor-agent/files/545863/ssh.txt)

**Comment by romanz** [comment]
Could you please add the log of the Bash commands you have used to reproduce the error?

**Comment by romanz** [comment]
I noted that your log file is missing "`debug2: key: [...]`" lines (see the attached [ssh-log.txt](https://github.com/romanz/trezor-agent/files/546319/ssh-log.txt), for `key: ssh://foobar (0x7f31374769f0)` line). 
There lines should tell us which public keys are being presented to the server by the `ssh` binary.
One of them should be the public key generated by `trezor-agent`.

**Comment by fansari** [comment]
=== Succesful login on first console ===

[fansari@bat ~]$ trezor-agent -v -s moon
2016-10-23 14:20:16,919 INFO         getting "ssh://moon" public key (nist256p1) from ledger...                                           [client.py:51]
=> 8002000115058000000db7e3cf21bfcdf956ea5424a4ded1fd68
<= 41041b6e586a2598588fd4ffa3470546446c59a950e7b36b9144b9ee0ce78855ff595b0cb88aeb1093c71eece8e02b45092766d56a45ff97490f672ae1f4cff673ec9000
2016-10-23 14:20:19,419 INFO         using SSH public key: cd:45:41:ca:58:41:4c:21:3b:de:6f:50:25:40:27:ba                                [__main__.py:110]
2016-10-23 14:20:19,423 INFO         running '/bin/bash' with {'SSH_AUTH_SOCK': '/tmp/ssh-agent-oQDU0n', 'SSH_AGENT_PID': '9840'}         [server.py:140]
[fansari@bat ~]$ ssh-add -L
Error connecting to agent: No such file or directory
[fansari@bat ~]$ export SSH_AUTH_SOCK=/tmp/ssh-agent-oQDU0n
[fansari@bat ~]$ export SSH_AGENT_PID=9840
[fansari@bat ~]$ ssh-add -L
ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBBtuWGolmFiP1P+jRwVGRGxZqVDns2uRRLnuDOeIVf9ZWwy4iusQk8ce7OjgK0UJJ2bVakX/l0kPZyrh9M/2c+w= ssh://moon
[fansari@bat ~]$ ssh moon
2016-10-23 14:21:29,959 INFO         please confirm user "fansari" login to "ssh://moon" using ledger...                                  [client.py:71]
=> 80040081e8058000000db7e3cf21bfcdf956ea5424a4ded1fd680000002079dcb3dce2cec4a137b6668e3fdf448b5d7360e7eda62300904872ac81616fbf320000000766616e736172690000000e7373682d636f6e6e656374696f6e000000097075626c69636b6579010000001365636473612d736861322d6e69737470323536000000680000001365636473612d736861322d6e69737470323536000000086e6973747032353600000041041b6e586a2598588fd4ffa3470546446c59a950e7b36b9144b9ee0ce78855ff595b0cb88aeb1093c71eece8e02b45092766d56a45ff97490f672ae1f4cff673ec
<= 304402201b3cb2a26de25dc4f2b5cb5c71d73d1c5f58986178c0e2b5db19616b09f19b63022062901d883abbe99a4e79676efaec5dd1bf252b027b452293070059fbf71f242a041b6e586a2598588fd4ffa3470546446c59a950e7b36b9144b9ee0ce78855ff595b0cb88aeb1093c71eece8e02b45092766d56a45ff97490f672ae1f4cff673ec9000
2016-10-23 14:21:35,610 INFO         signature status: OK                                                                                 [protocol.py:151]
Last login: Sun Oct 23 12:12:42 2016 from 192.168.30.1
[fansari@moon ~]$ 

=== Unsuccessful login on second console ===

fansari@bat ~]$ export SSH_AUTH_SOCK=/tmp/ssh-agent-oQDU0n
[fansari@bat ~]$ export SSH_AGENT_PID=9840
[fansari@bat ~]$ ssh-add -L
^C
[fansari@bat ~]$ ssh moon
^C
[fansari@bat ~]$ 

Here I had to press ^C because the commands are hanging.

Please also note that I use "Ledger Nano S" as hardware stick.

**Comment by romanz** [comment]
It seems that the first `ssh` connection doesn't close the `ssh-agent` socket after the authentication (note the missing `goodbye agent` message from the first `ssh moon` log).
BTW, which SSH version are you using (`ssh -V`)?

**Comment by romanz** [comment]
The fix should be easy though - just handle multiple connections in parallel, while holding a mutex for device-related operations.

**Comment by romanz** [comment]
Please try commit https://github.com/romanz/trezor-agent/commit/97efdf4a45d503ec776d89c427f1b4a1522f2aa4 (from https://github.com/romanz/trezor-agent/commits/concurrent-handler branch). It should allow handling new singature requests, even if the previous connections are kept alive.

**Comment by fansari** [comment]
I haved tested it. This is an improvement. I can now login with more than one shell.
But: this is only true if I login multiple times to the same machine. 

How can I use the trezor-agent to have multiple ssh sessions to multiple hosts?

**Comment by romanz** [comment]
Currently it's not supported, since the SSH identity is specified once, when launching `trezor-agent` :(
The tracking issue for this bug (using `trezor-agent` concurrently with multiple identities) is #34.

**Comment by romanz** [comment]
Please try [refactor-device](https://github.com/romanz/trezor-agent/commits/refactor-device) branch (following #70 PR).
