### ISSUE TITLE
Error with ./scripts/gpg-init on OS X

### ISSUE THREAD

**Issue by oohaysmlm** [romanz/trezor-agent#69]
Latest version of trezor-agent gpg-init script will not run on osx due to differences in sed options.

Need to change FINGERPRINT line from:
```
FINGERPRINT=$(gpg2 --homedir "${HOMEDIR}" --list-public-keys --with-colons | sed --quiet --regexp-extended 's/^fpr:::::::::([0-9A-F]+):$/\1/p' | head -n1)
```

To:
```
FINGERPRINT=$(gpg2 --homedir "${HOMEDIR}" --list-public-keys --with-colons | sed -n -E 's/^fpr:::::::::([0-9A-F]+):$/\1/p' | head -n1)
```

Hope this can help someone else :).  Thanks for the trezor-agent Roman.

**Comment by romanz** [comment]
Thanks for reporting this issue :)
