### ISSUE TITLE
SSHFS usage

### ISSUE THREAD

**Issue by ulrichard** [romanz/trezor-agent#72]
Can this also be used for sshfs?
If not, that would be cool.

**Comment by romanz** [comment]
That's indeed a good question!
It should probably work - will test it tomorrow :)

**Comment by ulrichard** [comment]
Cool, it somehow  works, but it's blocking.
It works in a second console for as long as the trezor-agent process is alive. When I terminate the blocking process with Ctrl+c, it is immediately unmounted.
This behaviour is different from raw sshfs, and it's not so cool for scripts like: https://github.com/ulrichard/locally_encrypted_remote_storage/blob/master/open_locally_encrypted_remote_storage.sh
Is there another option than appending an '&' to the command line?

**Comment by romanz** [comment]
This indeed sounds like a problem...
I'll take a look.

**Comment by romanz** [comment]
Could you please elaborate what exactly is blocking?
Does the following command block?
```
$ trezor-agent -v localhost -- sshfs localhost:/home/roman /tmp/mnt
```
On my machine, it blocks only until I confirm the connection on the TREZOR, and then it finishes, the SSHFS mount works correctly ([screencast](https://asciinema.org/a/27ojy2v7kljw6v8xcnrbrh95x)).

Also, which OS and SSH versions are you using? 
```
$ uname -a
$ ssh -V
$ sshfs -V
```

**Comment by ulrichard** [comment]
Yes it's exactly that command that does not return.
`
richi@XPS13ulr:~$ uname -a
Linux XPS13ulr 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
richi@XPS13ulr:~$ ssh -V
OpenSSH_7.2p2 Ubuntu-4ubuntu2.1, OpenSSL 1.0.2g  1 Mar 2016
richi@XPS13ulr:~$ sshfs -V
SSHFS version 2.5
FUSE library version: 2.9.4
fusermount version: 2.9.4
using FUSE kernel interface version 7.19
`

**Comment by romanz** [comment]
My versions are a bit different:
```
$ sshfs -V
SSHFS version 2.5
FUSE library version: 2.9.3
fusermount version: 2.9.3
using FUSE kernel interface version 7.19
$ ssh -V
OpenSSH_6.7p1 Debian-5+deb8u3, OpenSSL 1.0.1t  3 May 2016
$ uname -a
Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux
```

BTW, I managed to reproduce this behaviour by running:
```
trezor-agent -v localhost -- sshfs -f localhost:/home/roman /tmp/mnt
```
(note the `-f` flag - causing the `sshfs` to stay in foreground).

**Comment by romanz** [comment]
You can use the `-s` command line [flag](https://github.com/romanz/trezor-agent/blob/master/trezor_agent/__main__.py#L51), in order to run `sshfs` in the background.
See [here](https://asciinema.org/a/ecg7c8gn5vycypgxje1ea9cu2) for sample usage.

**Comment by ulrichard** [comment]
That all works nicely with an interactive console, but so far I couldn't figure out how to use it in a script.

**Comment by romanz** [comment]
You're right, it's quite hard to use it that way in a non-interactive script...

BTW, could you reproduce this issue using regular SSH keys (without `trezor-agent`):
```
$ ssh-keygen -f /tmp/key
$ ssh-keygen -yf /tmp/key > ~/.ssh/authorized_keys
$ ssh-add /tmp/key
$ sshfs localhost:/home/roman /tmp/mnt   # <- Does this block (when using regular ssh-agent)?
$ sudo umount /tmp/mnt
```

**Comment by ulrichard** [comment]
I didn't try with the standard ssh-agent yet, but I use it on a daily basis with gpg-agent acting as ssh-agent. It doesn't block there. 
I have to say though, it works flawlessly on ubuntu 12.04 all the way through 16.04. But on 16.10 I didn't get the setup to work correctly yet.

**Comment by romanz** [comment]
Are there any updates about the Ubuntu 16.10 issue?

**Comment by romanz** [comment]
@ulrichard Ping :)
