### ISSUE TITLE
Mac - GPG no longer working

### ISSUE THREAD

**Issue by fruitloop** [romanz/trezor-agent#78]
Hi, I just tried to use the trezor agent like this:

```
export TREZOR_GPG_USER_ID="my_id"; trezor-gpg agent
2016-11-20 16:44:31,984 WARNING    This GPG tool is still in EXPERIMENTAL mode, so please note that the API and features may change without backwards compatibility!
```

and in another window I try the following:
```
echo 'foo' | gpg2 --sign -u 'my_id' | gpg2 --verify
gpg: skipped 'my_key': No secret key
gpg: signing failed: No secret key
gig: verify signatures failed: Unknown system error
```

am I doing something wrong?

Best regards
Roland

**Comment by fruitloop** [comment]
interesting. I updated trezor-agent via pip
and started the tremor-gpg agent with an -v flag and now it works again.

**Comment by romanz** [comment]
Glad it works for you :)

By the way, the latest version is using [gpg-init](https://github.com/romanz/trezor-agent/blob/master/scripts/gpg-init) and [gpg-shell](https://github.com/romanz/trezor-agent/blob/master/scripts/gpg-shell) for easier creation and usage of your GPG keys.
You can see a demo screencast [here](https://github.com/romanz/trezor-agent/blob/master/README-GPG.md#quickstart).

**Comment by fruitloop** [comment]
I saw that. But when I clone the repository and try the script I get:

```
./gpg-shell
gpg-connect-agent: invalid option "--agent-program"

**Comment by romanz** [comment]
What version of `gpg-connect-agent` are you using?

```
$ gpg-connect-agent --version
gpg-connect-agent (GnuPG) 2.1.16
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /home/roman/.gnupg
```

**Comment by romanz** [comment]
It seems to be mentioned on the `man` page for `gpg-connect-agent`:
```
$ man gpg-connect-agent | grep agent-program -A3
       --agent-program file
              Specify  the agent program to be started if none is running.  The default value is determined by running gpgconf with the option --list-dirs.  Note that the pipe symbol (|) is used for a regression test suite hack and
              may thus not be used in the file name.
```

**Comment by fruitloop** [comment]
```
gpg-connect-agent (GnuPG) 2.1.15
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /Users/roland/.gnupg
```

**Comment by romanz** [comment]
Very weird... I'll try to see if there is another option to start our custom gpg-agent automatically.

**Comment by romanz** [comment]
In the meanwhile, you can replace the [call](https://github.com/romanz/trezor-agent/blob/master/scripts/gpg-shell#L10) to `gpg-connect-agent` by the following line:
```
killall trezor-gpg-agent; trezor-gpg-agent &
```
A bit hacky, but will probably work :)

**Comment by romanz** [comment]
By the way, could you try to build GPG 2.1.15 according to the following [instructions](https://gist.github.com/vt0r/a2f8c0bcb1400131ff51), and retry calling:
```
gpg-connect-agent --agent-program "$(which trezor-gpg-agent)"
```
I suspect there is some difference between our GPG installations...

**Comment by fruitloop** [comment]
Hi, I managed to update gpg-connect-agent. It was installed, but another version was used by default.

I changed you script to `/usr/local/bin/gpg-connect-agent` rather than `gpg-connect-agent`.

Now I have one problem.

How do I initialize it when I already have the GPG Keys? On another Mac I already initialized the Keys and I wrote down the --timestamp value in order to recreate them.

Is there a way I can call the `gpg-init` script with that timestamp?

**Comment by romanz** [comment]
You can use the following format to re-generate the key:
```
TIMESTAMP=1234567890 ./scripts/gpg-init "John Doe <john.doe@gmail.com>"
```

**Comment by fruitloop** [comment]
Thanks, I looked more closely at the script and rewrote it completely to import all of my 4 keys at once. I have some troubles at the moment, I'll post them if I can't fix them on my own.

**Comment by fruitloop** [comment]
Ok I thing I found an error:

I called `trezor-gpg-create` and it seems to crash.
```
trezor-gpg-create -e "nist256p1" -t my_timestamp -v "Roland Planitz <roland@planitz.at>"
...
2016-11-24 23:27:39,402 INFO         adding nist256p1 GPG subkey for "Roland Planitz <roland@planitz.at>" to existing key                 [__main__.py:38]
2016-11-24 23:27:39,416 INFO         please confirm GPG signature on Trezor for "Roland Planitz <roland@planitz.at>"...                   [client.py:31]
Traceback (most recent call last):
  File "/usr/local/bin/trezor-gpg-create", line 11, in <module>
    load_entry_point('trezor-agent==0.8.0', 'console_scripts', 'trezor-gpg-create')()
  File "build/bdist.macosx-10.11-x86_64/egg/trezor_agent/gpg/__main__.py", line 93, in main_create
  File "build/bdist.macosx-10.11-x86_64/egg/trezor_agent/gpg/__main__.py", line 50, in run_create
  File "build/bdist.macosx-10.11-x86_64/egg/trezor_agent/gpg/encode.py", line 99, in create_subkey
  File "build/bdist.macosx-10.11-x86_64/egg/trezor_agent/gpg/protocol.py", line 266, in make_signature
  File "build/bdist.macosx-10.11-x86_64/egg/trezor_agent/gpg/keyring.py", line 227, in sign
  File "build/bdist.macosx-10.11-x86_64/egg/trezor_agent/gpg/keyring.py", line 171, in sign_digest
ValueError: ERR
```

**Comment by romanz** [comment]
Closing this, as it seems that the original problem (related to `gpg-connect-agent`) is solved.
