### ISSUE TITLE
MacPro installation fails to create `trezor-*` utilities

### ISSUE THREAD

**Issue by fruitloop** [romanz/trezor-agent#79]
Hi, on my MacBook Air I installed trezor-agent probably a month ago via pip install from the this git repository. That gave me the following tools:
```
/usr/local/bin/trezor-agent
/usr/local/bin/trezor-gpg
/usr/local/bin/trezor-git
```

On my MacPro however this wont  work anymore. There are no tools installed. 
What is the proper way to install the agent at the moment?

Also the `trezorctl` command is no longer availlable.

Best regards
Roland

**Comment by romanz** [comment]
Unfortunately, I don't have a Mac to debug the issue :(

**Comment by fruitloop** [comment]
So it seems that this is not a known behaviour due to updates?

**Comment by romanz** [comment]
I think it's a Python-related issue - and not something that the latest changes may cause.

**Comment by fruitloop** [comment]
I found the problem.
When I'm installing the packet using PIP it won't create the `trezor-*` packages.

When I clone the repository however and run `python setup.py build && python setup.py install` myself it creates all the necessary `trezor-*` packages.

**Comment by romanz** [comment]
Thanks for reporting this!
I'll fix the README.
