### ISSUE TITLE
GPG Agent Key Format

### ISSUE THREAD

**Issue by fruitloop** [romanz/trezor-agent#80]
Hi, 

when I'm using my Trezor for SSH it gives me a nice format like:

```
SSH login to:
servername:22
user: fancyuser
```

All info nicely distributed over the display.

With GPG however I get something like:

```
GPG login to:
Firstname Lastname <firstna
```

the email address is barely visible.
I would much more prefer a format like with SSH maybe something like:

```
GPG login to:
Firstname Lastname
firstname@lastname.com
```

Is that something that could be done? I use several different Keys which differ only in the email address which in that case is hardly visible.

Best regards
Roland

**Comment by romanz** [comment]
Thanks for the suggestion!
This is actually a very useful feature :)

Just to make sure I understand your use-case:
Are you using separate GPG signature/encryption keys for different identities?
Or, do you have multiple user IDs attached to the same GPG keypair?

**Comment by romanz** [comment]
BTW, could you post the output of `gpg2 -k` for your GPG identity, so I could understand better your scenario?

For example, my TREZOR-based GPG identity has a signature key, an encryption key and a single user ID:
```
$ gpg-shell gpg2 -k
/home/roman/.gnupg/trezor/pubring.kbx
-------------------------------------
pub   nistp256 2016-10-29 [SC]
      15C8C3574AE4F1E25F3F35C587CAE5FA46917CBB
uid           [ultimate] Roman Zeyde <roman.zeyde@gmail.com>
sub   nistp256 2016-10-29 [E]
```

**Comment by fruitloop** [comment]
I don't like sub ids, so I basically have one key per email-address that serves a specific purpose:

```
pub   nistp256 2016-10-16 [SC]
      A9FC726432034F32071549BF44F2BB535E654B16
uid           [ultimate] Roland Planitz <roland@planitz.at>
sub   nistp256 2016-10-16 [E]

pub   nistp256 2016-10-16 [SC]
      79301D1B58944DCF88EB052977F58D0A71D73E81
uid           [ultimate] Roland Planitz <keysigning@planitz.at>
sub   nistp256 2016-10-16 [E]

pub   nistp256 2016-11-24 [SC]
      582F0423D8DC188286710E0638025144D28FFA95
uid           [ultimate] Roland Planitz <codesigning@planitz.at>
sub   nistp256 2016-11-24 [E]
```

Usage as stated in email, private key, keysigning key and codesigning key. 
Therefore the relevant part (first part of email address is cut off almost every time ;))

**Comment by romanz** [comment]
Thanks for the quick reply!
It's indeed a good use-case, which I didn't consider before...
I'll look through the code and see what can be done to support it.

**Comment by romanz** [comment]
@prusnak @saleemrashid
What do you think?

**Comment by prusnak** [comment]
I think it's a good idea to split

`Firstname Lastname <firstname@lastname.com>` (which does not fit)

into

```
Firstname Lastname
<firstname@lastname.com>
```

**Comment by fruitloop** [comment]
Maybe even:

```
Firstname Lastname
firstname@lastname.com
```

That way we win another two characters and the <> chars are basically only usefull if the User Id is displayed in one line.

**Comment by prusnak** [comment]
Right!

**Comment by saleemrashid** [comment]
@prusnak Correct me if I'm wrong, but this would have to be an exception in the trezor-mcu code. Just want to get everything clear and aleviate confusion :smile:

**Comment by prusnak** [comment]
Yes.

**Comment by fruitloop** [comment]
Hi, any news yet?

**Comment by romanz** [comment]
The discussion has moved to https://github.com/trezor/trezor-mcu/pull/132.
Currently, we don't have a good way to implement this feature without introducing non-trivial changes to the existing firmware and/or protocol definitions :(

**Comment by romanz** [comment]
Merged at https://github.com/trezor/trezor-mcu/commit/466155270ba0b356ffb1938f5bcccbaf1a6f7e20.
Thanks @prusnak!

**Comment by fruitloop** [comment]
I saw some merges and the issue is closed, so I updated `python-trezor` as well as `trezor-agent` and still the old format on the display of the trezor.

Am I doing something wrong?

**Comment by prusnak** [comment]
@fruitloop are you using freshly built firmware from master?

**Comment by fruitloop** [comment]
I did:
```
cd python-trezor
git checkout master
git pull
python setup.py build
python setup.py install
```
and then the same with `trezor-agent`

**Comment by prusnak** [comment]
@fruitloop but you did not update the firmware, which is kind of necessary for a firmware change.

**Comment by fruitloop** [comment]
oh, well that makes sense,
I tried to upgrade the firmware by holding both hardware buttons and connecting it while in the `trezor.io` webwallet.

but the old view is still shown on display.

How can I `force` the newest firmware update to be installed?

**Comment by prusnak** [comment]
The new one is not official yet. It's not released yet.

**Comment by fruitloop** [comment]
Thanks, I'll wait for now

**Comment by romanz** [comment]
The new firmware can be downloaded from [here](https://github.com/trezor/webwallet-data/blob/master/firmware/trezor-1.4.2.bin).

**Comment by fruitloop** [comment]
Thanks, works like a charm
