### ISSUE TITLE
Plans to add RSA Support?

### ISSUE THREAD

**Issue by PowerPress** [romanz/trezor-agent#84]
Plans to add RSA GPG support for those than do not trust elliptic curves? Thats main thing Yubikey and OpenPGP Smartcards have going for them.

**Comment by romanz** [comment]
AFAIK, there are no current plans to add RSS support to TREZOR:
https://www.reddit.com/r/TREZOR/comments/3l8kxg/ssh_now_possible_with_trezor/cv4nsql
