### ISSUE TITLE
Feature: Add non-blocking listener option

### ISSUE THREAD

**Issue by xenithorb** [romanz/trezor-agent#89]
This would be for implementing with various scripts and/or as the default system's SSH agent. 

Currently I do something like this in my ~/.bashrc (im a ledger user, hence the `2c97` id): 

```bash 
is_trezor_agent_session() {
        local path_check=$( command -v trezor-agent )
        local trezor_virtual="$HOME/virtualenvs/ledger/bin/trezor-agent"
        if [[ $path_check ]]; then
                TREZOR_AGENT_BIN="$path_check"
        elif [[ -x $trezor_virtual ]]; then
                TREZOR_AGENT_BIN="$trezor_virtual"
        fi
        alias trezor-agent="$TREZOR_AGENT_BIN"
        if [[ ${SSH_AUTH_SOCK,,} =~ trezor ]] \
        || ! lsusb -d 2c97: >/dev/null 2>&1; then
                return 1
        fi
        return 0
}

if is_trezor_agent_session; then
        "$TREZOR_AGENT_BIN" -se ed25519 -- example@example.com
fi

```

The drawback to this is that if the device is present, the new interactive shell runs `trezor-agent` and blocks the terminal on waiting for the key. 

What I would like to see is:

1. An option that starts a non-blocking mode (other similar agents sit in the background and wait for keys to be added)
2. In the above mode other keys can be added (agent mode)
    - Optionally, a client mode that adds keys to other agents (I'm not sure if this is possible given the hardware)
3. In non-blocking mode, `trezor-agent` would then listen for the USB device to be connected, and auto-magically ask the device for the key corresponding to a pre-entered id 
    - Example:

       ```
       trezor-agent -n -e ed25519 -i 2c97 -- example@example.com
       ```

       Would immediately wait in the background for a USB device vendor of `2c97` (as to support more than just TREZOR) and would query that device for the id `example@example.com`. In this instance, the user would need to know (or perhaps not, it could be quick enough) that the device is going to ask for a confirmation immediately after entering the SSH app.

4. Non-blocking mode should output a socket to be used with exporting with `SSH_AUTH_SOCK`, like other agents

**Comment by romanz** [comment]
Thanks for the suggestion, this is a really good feature!

**Comment by romanz** [comment]
Just to make sure I understand - you'd like to emulate the standard `ssh-agent`/`ssh-add` behaviour:
`ssh-agent` runs in the background, and the user adds/removes SSH identities using `ssh-add`-like tool.

**Comment by romanz** [comment]
@xenithorb Ping?

**Comment by xenithorb** [comment]
That's correct. I want a way for it to cooperate more easily with being integrated into the X environment in a true "agent" fashion. I find it very difficult to use this in a serious normal capacity without the features I listed above. 

The non-blocking part is crucial (and this is what I did my best to approximate in bash) because currently with the way the software is engineered, it essentially is running layered bash prompts, and when it comes time to execute `--shell` it will hang if the device is not present or if you user doesn't interact. I'd rather the agent just fail if it can't find a suitable way to provide a key, and "not block" the loading of the terminal, much the same way the standard ssh-agent would work if no keys were loaded.

**Comment by romanz** [comment]
@xenithorb Please take a look at https://github.com/romanz/trezor-agent/commit/43c424a4021adbd5b08f56e2ec0c084ce8794588 - it should provide initial "async" behaviour for `trezor-agent`.

**Comment by xenithorb** [comment]
I would love to but my nano S board is literally in pieces today, so It may be some time before I can test again. I'm waiting on new switches, and as soon as I get those soldered on I'll test. Thanks

**Comment by romanz** [comment]
Ping :)

**Comment by xenithorb** [comment]
Ah yes, thanks for the ping I'll leave the alert up to remind me tomorrow. Test as soon as I can!

**Comment by xenithorb** [comment]
Hi, pulled my ledger out of storage to give this thing a try again, and I had to update my snippet after noticing the new package split.

The updated snippet is:

```bash
is_ledger_agent_session() {
	local a path_check=$(
		a=$(command -v ledger-agent) \
		&& [[ "$a" =~ alias ]] \
		|| printf '%s' "$a"
	)
	local ledger_virtual="$HOME/virtualenvs/ledger/bin/ledger-agent"
	if [[ $path_check ]]; then
		LEDGER_AGENT_BIN="$path_check"
	elif [[ -x $ledger_virtual ]]; then
		LEDGER_AGENT_BIN="$ledger_virtual"
	fi
	alias ledger-agent="$LEDGER_AGENT_BIN"
	if [[ ${SSH_AUTH_SOCK,,} =~ (ledger|trezor) ]] \
	|| ! lsusb -d 2c97: >/dev/null 2>&1; then
		return 1
	fi
	return 0
}

if is_ledger_agent_session; then
	"$LEDGER_AGENT_BIN" -se ed25519 -- example@example.com
fi
```
This actually works OK. 

First, how it works currently..... I start a new bash login, this function activates when the ledger is plugged in, and runs a **new** shell underneath the `ledger-agent` process. This works great in that it falls back to the terminal immediately without poking the ledger quite yet, and if I `ssh` to any host, that is the moment when I need to push the button - perfect. The downside is that I'm running two shells (one parent, ledger-agent, and one under ledger-agent).

Things left to be desired (how I want it to work)...

1. I really just want it to have the capability to behave like `ssh-agent`, where ordinarily you could type `eval $(ssh-agent)` in the commandline, and you're ready to go, and with that it's also really easy to integrate into environments like with `.bashrc` because it already outputs the necessary exports.

    I tried fudging it with

    ```bash 
    eval $(SHELL='/usr/local/bin/foo.sh' ledger-agent -s example@example.com)
    ```

    Where `/usr/local/bin/foo.sh` does `echo $SSH_AUTH_SOCK` immediately and then is a long-running (infinite) process to keep `ledger-agent` from exiting. It's incredibly hard to figure out how to daemonize this, essentially. I could never get it to background properly in order to just consume the agent socket name and then fall back to the original terminal. 

2. Configurable socket path, demonizing - KeeAgent for example, I'm able to start it once with my Desktop Environment, and from that moment it makes a _known socket_ that I have preconfigured `SSH_AUTH_SOCK` to point to. The result is that I can load Keepass, login, and open a terminal and my ssh-agent (a function of the keepass plugin) is active and working because my environment is setup to use the _known socket_. Problems arise when you can't configure the path of the socket due to the fact that the only natural way to use it is to spawn processes from _it's_ environment, which is where the problems lie for me in trying to use this. Ideally I want to be able to daemonize it and also have my environment point to a known (configurable) socket path so we don't have to do gymnastics with the environment.

**Comment by romanz** [comment]
Thanks for the suggestions, @xenithorb !

**Comment by romanz** [comment]
Please take a look at the latest release [v0.9.8](https://pypi.python.org/pypi/libagent/0.9.8) - it should support both daemonizing (via `-d` flag) and socket path setting (via `--sock-path` flag).

**Comment by xenithorb** [comment]
Hi again and thank you for your hard work getting this issue resolved. I will check on this soon (added to my TODO list), and wanted to drop a line letting you know I haven't forgotten about it.

**Comment by romanz** [comment]
You're welcome :)
