### ISSUE TITLE
Install fails because Pillow fails?

### ISSUE THREAD

**Issue by Mqrius** [romanz/trezor-agent#90]
I don't have a properly formatted bug report for this one, sorry.

I tried following the installation instructions as listed [here](https://github.com/romanz/trezor-agent/blob/master/README.md), but pip install trezor_agent failed. So I tried to install from source as listed in the same instructions, but that failed as well.

I don't have a full understanding of why it failed, but there seemed to have been an issue with installing the Pillow dependency. I made it work by following some instructions [here](https://stackoverflow.com/questions/34631806/fail-during-installation-of-pillow-python-module-in-linux), specifically I ran
`sudo apt-get install libtiff5-dev libjpeg8-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python-tk`
And then tried installing my build of trezor-agent again; this time it worked.

To my best understanding, there is an issue with the automatic installation of dependencies for Pillow, possibly specifically with zlib. This isn't really Trezor's fault of course, but perhaps it would be helpful to have the trezor-agent installation instructions instruct the user to install both zlib and Pillow as separate things, not just automatically as a dependency for trezor-agent.

**Comment by romanz** [comment]
Thanks a lot for reporting this issue!
AFAIU, this dependency is added by [ledger package](https://pypi.python.org/pypi/ledgerblue) - but it seems that it isn't actually used there:
https://github.com/LedgerHQ/blue-loader-python/search?utf8=%E2%9C%93&q=PIL

@btchip Could you please take a look if this dependency can be removed from [here](https://github.com/LedgerHQ/blue-loader-python/blob/master/setup.py#L18)?

**Comment by btchip** [comment]
PIL is used by the build system when compiling applications - so while it's not strictly required for the communication API, it's still part of a basic set needed for development. I'll see if it's possible to split it but would rather avoid it if there's a way to make it easier to install

**Comment by Mqrius** [comment]
You could try adding zlib independently to the trezor-agent dependencies
before the ledger dependency? Would that work?

**Comment by romanz** [comment]
@Mqrius The [link](https://stackoverflow.com/questions/34631806/fail-during-installation-of-pillow-python-module-in-linux) above suggest upgrading `pip` before installing `Pillow` (to support wheel-based installation).
Could you please try that to see if it also can solve the issue?

**Comment by Mqrius** [comment]
IIRC I did actually try that but it didn't solve the issue. I'm not quite
fluent enough to make this a proper bug report either; maybe it's more
effective to see if you can reproduce the issue? Something like a fresh
virtual machine and then trying to just install only trezor-agent from
scratch, maybe that would do it.

**Comment by romanz** [comment]
Sounds good.
Which Linux distribution did you use?

**Comment by Mqrius** [comment]
Ubuntu 14.04.5 LTS (trusty)

**Comment by romanz** [comment]
Upgrading PIP to to the latest version (9.0.1) seems to do the trick:
https://gist.githubusercontent.com/romanz/af44ac1f4f793c667f8717fb28698fd4/raw/18b97cf111c1badabf7d696924db46618c869052/trezor-agent-on-ubuntu-14.04.5
