### ISSUE TITLE
Suggest : create homebrew package for OSX

### ISSUE THREAD

**Issue by harobed** [romanz/trezor-agent#92]
Suggest : create homebrew package for OSX

**Comment by fruitloop** [comment]
From what I remember, creating a Homebrew Package should not be that hard since you just have to point to a source of data and give instructions how to install them.

**Comment by romanz** [comment]
Unfortunately, I don't have a Mac OS X machine for creating a homebrew package...
Any pull requests are welcome :)

**Comment by galuszkak** [comment]
I can create that package. :)

Taking that ticket then ;)

**Comment by romanz** [comment]
Much appreciated :)

**Comment by galuszkak** [comment]
@romanz found this:
https://github.com/tdsmith/homebrew-pypi-poet

sounds it's taking care of everything for creating Formula.

**Comment by romanz** [comment]
Thanks for finding this tool :)
Running it on my machine resulted in the following [formula](https://gist.github.com/romanz/8feb3357e12f4581c79b19c2090a4918).
If this works for you, feel free to submit a PR for https://github.com/Homebrew/homebrew-core (IIUC).

**Comment by talmai** [comment]
Using your .rb worked. trezor-agent built with minimal hassles.

**Comment by menteb** [comment]
Has the formula been submitted?

**Comment by romanz** [comment]
Oops... forgot to do that :)
@galuszkak could you please submit the PR to https://github.com/Homebrew/homebrew-core?

**Comment by menteb** [comment]
@romanz @galuszkak I'm testing it on my machine as we type. I can submit it through git if you want. Just one command away

**Comment by romanz** [comment]
@menteb many thanks for testing!
If it works for you - please submit the PR.

**Comment by menteb** [comment]
Done: https://github.com/Homebrew/homebrew-core/pull/22537
Thanks for the great job, @romanz

**Comment by menteb** [comment]
Didn't pass the tests, though it worked fine on my Mac:
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/16090/
Will start digging in. @galuszkak, any ideas?

**Comment by menteb** [comment]
Aha, someone came back to me. We need to include a test for the formula to pass. Is there a certain command line test for trzer-agent that has an output to verify whether the binary works correctly?

**Comment by romanz** [comment]
Following #182, it does support `--version` flag now :)

**Comment by menteb** [comment]
@romanz is that still 0.9.0? Guess not... Is there another more current version I can refer to in the Brew formula? Right now this is the link:

url "https://files.pythonhosted.org/packages/90/29/f840f2d498c1880e3fe00a8985da7ae9ad5afff16de0d046ade3e849f098/trezor_agent-0.9.0.tar.gz"
  sha256 "7f71ddd4b46805eab2bdb99fcd9274115d7264a4535e004cf5800d47ab6aacc4"

Guess that needs updating.

**Comment by romanz** [comment]
Most of the functionality is at `libagent` [package](https://github.com/Homebrew/homebrew-core/pull/22537/files#diff-60467aa39dd17ec734b1672768143961R47); the `trezor_agent` [package](https://github.com/romanz/trezor-agent/tree/master/agents/trezor) contains only the TREZOR-specific scripts' definitions.

I have uploaded the latest (0.9.7) `libagent` package to [PyPI](https://pypi.python.org/packages/23/ea/3ebcfe3ada6e4f5959ad5a15d7d5daa29577a88abb163d45d4986132b399/libagent-0.9.7.tar.gz#md5=5b8221de054a0114acc22a6ade169c51), containing the `--version` flag support.

**Comment by menteb** [comment]
@romanz success! Waiting for a maintainer to merge now. It passed all checks :)
Had some cool help, and now all works. 
For reference: https://github.com/Homebrew/homebrew-core/pull/22537

I can keep maintaining the brew part if you want.

**Comment by romanz** [comment]
@menteb Great news!
Thanks a lot for the help, and it would be great if you could help me maintaining the Homebrew package :)

**Comment by menteb** [comment]
The --version still shows trezor-agent=0.9.0 libagent=0.9.7 instead of libagent=0.9.8.
Got an update to home-brew ready, though still waiting for a maintainer to merge.

**Comment by talmai** [comment]
We should close this :)
