### ISSUE TITLE
Is It possible to keep authenticate ssh validation for some time?

### ISSUE THREAD

**Issue by harobed** [romanz/trezor-agent#94]
Hi,

I test trezor-agent with Ledger Nano S.

```
$ trezor-agent root@example.com --shell
$ ssh root@example.com
```

It works fine but I need to click on SSH Agent Authenticate confirmation on Ledger device each time #ssh command is executed.

I use Ansible scripts that does a lot of ssh calls. Is it possible to set a timeout to avoid validate each request in trezor-agent or Ledger ?

Best regards,
Stéphane

**Comment by romanz** [comment]
You can use SSH multiplexing:
https://en.wikibooks.org/wiki/OpenSSH/Cookbook/Multiplexing#Setting_Up_Multiplexing

**Comment by romanz** [comment]
I can suggest using the following settings in `~/.ssh/config`:
```
ControlMaster auto
ControlPath ~/.ssh/ssh-%r@%h:%p.sock
ControlPersist 60
```
