### ISSUE TITLE
GPG thinks there are private keys for all public keys

### ISSUE THREAD

**Issue by pafcu** [romanz/trezor-agent#96]
When I import some public keys, and then do `gpg --list-secret-keys` I get a list of secret keys that I definitely do not have. This confuses some programs which then pick the wrong key for signing and encrypting. It is also not possible to remove these keys (`delete key failed: End of file`)

**Comment by romanz** [comment]
Thanks for reporting this issue!

**Comment by romanz** [comment]
Could you please attach the commands you have ran, that resulted in the problem above?

**Comment by pafcu** [comment]
First run `scripts/gpg-shell` then `gpg --import` using any(?) key file (I have tried with multiple ones). This is on openSUSE with gpg (GnuPG) 2.1.18. I don't remember anymore what I did to initialize `trezor_agent` but I can probably try to start from the beginning again. But I did create a key using the trezor, and I can sign and encrypt things using it.

My goal is to import some external keys and sign them using the Trezor.

**Comment by romanz** [comment]
Good catch, thanks!
I'll take a look on this during this week.

**Comment by pafcu** [comment]
Are you able to reproduce it, or should I try to test it more thoroughly?

**Comment by romanz** [comment]
I think that I understand the reason for this issue, but I'm currently not near my workstation... I will update later this week.

**Comment by romanz** [comment]
@pafcu Please take a look at the latest version (in the `master` branch):

```
$ gpg2 --list-keys
pub   nistp256/46917CBB 2016-10-29 [SC]
uid         [ultimate] Roman Zeyde <roman.zeyde@gmail.com>
sub   nistp256/DD5CFA1F 2016-10-29 [E]

pub   rsa4096/7D8D0BF6 2012-03-05 [SC] [expires: 2018-02-02]
uid         [ unknown] Kali Linux Repository <devel@kali.org>
sub   rsa4096/FC0D0DCB 2012-03-05 [E] [expires: 2018-02-02]

$ gpg2 --list-secret-keys
sec   nistp256/46917CBB 2016-10-29 [SC]
uid         [ultimate] Roman Zeyde <roman.zeyde@gmail.com>
ssb   nistp256/DD5CFA1F 2016-10-29 [E]

```

**Comment by pafcu** [comment]
Thanks, it seems to work now for newly imported keys. However, the old keys still have the same problem, and as I said earlier it is not possible to remove them. Is the only option to delete the keyring and recreate it? Is it possible to export my actual private key, and import it into the new keyring? Or do I have to reinitialize my identity from scratch, set the correct seed to get the same ID and add subkeys again?

**Comment by romanz** [comment]
I have tried to reproduce this issue (swiching the `False` [here](https://github.com/romanz/trezor-agent/blob/master/trezor_agent/gpg/agent.py#L117) to `True`), but it seems that killing `trezor-gpg-agent` and switching back to the original code seems to fix the issue (the imported keys are not listed as having a secret part, and can be deleted from the command-line)...

If it doesn't work for you, I suggest reinitalizing the GnuPG identity, using the timestamp value from the existing GnuPG identity - via the command below:
```
$ gpg2 --export | gpg2 --list-packets -v | grep "version 4" | grep "created"
```

**Comment by pafcu** [comment]
I can't actually reproduce this anymore myself, so possibly I did something wrong during previous testing. so, seems to have been fixed.
